requirements-setup.txt, requirements-test.txt, requirements.txt
#54 
The numpy version needs to be fixed to `1.14.*` because MXNet does not support versions 1.15.* or higher yet (fixes #54).
Also, align the contents of the requirements files with the Conda packages listed in the env folder that are used in the Jenkins pipelines.
=> Update requirements files

src/gluonts/model/r_forecast/_predictor.py
N/A
Computes the number of sequential observations in the target using `shape[0]` instead of `len()` as the former is valid for multi-dimensional arrays as well. 
=> fix forecast_start date computation for multivarite R forecasts.

src/gluonts/distribution/lds.py, test/distribution/test_lds.py
* The test for LDS was `@skip`'ed (!!!), now it's enabled
* By doing that I realized that the `sample` method of LDS was broken (the case where `num_samples=None` was not handled correctly), now the shaping problems are fixed
* The batch_shape/event_shape were also set wrong, now they are fixed and a docstring somewhat related to this has been updated
* Assertions in the test for LDS where improved/added
=> Fix LDS, improve test

src/gluonts/distribution/binned.py
Fixes #62 and #67.
List was used in a validated() constructor argument without element type, which trips up pydantic on some Python 3.7.x versions.
=> Fix issue with generic type in BinnedOutput

src/gluonts/distribution/binned.py, src/gluonts/distribution/distribution_output.py, test/distribution/test_distribution_inference.py
* The code for inference tests is simplified a bit.
* An assertion is added, to make sure the loss tensor has the expected ("batch") shape during SGD.
* Binned and BinnedOutput are fixed (for example, it is now hybridizable).
* A docstring in the DistributionOutput class is improved.
=> Simplify inference tests, fix Binned distribution

README.md
The README.md is used not just for GitHub, but also for PyPi, where the relative links of course do not work. This makes all links to other Github content absolute.
=> Make README.md links absolute for PyPi

Makefile
Addresses #66 
Disable the creating of directory entries in the zip file (which then omits empty directories as a side effect).
=> Add --no-dir-entries to zip file creation to prune empty directories

src/gluonts/transform.py
Fixes #78
Fix lost frequency in pandas timestamp
=> fix lost freq of pandas timestamp

src/gluonts/dataset/artificial/_base.py, src/gluonts/distribution/binned.py
Fix issue #82 
The hour and minute random values were out of bound since the `random.Random.randint(low, high)` gives samples with the limits inclusive (`numpy` does not). 
=> fix artificial dataset bug

src/gluonts/dataset/artificial/_base.py, src/gluonts/dataset/repository/_lstnet.py, src/gluonts/dataset/split/splitter.py, src/gluonts/dataset/util.py
Using pd.DatetimeIndex for generating a time index as a date range is deprecated and it raises a FutureWarning with pandas 0.24.2. All relevant instances in the codebase are replaced with pandas.date_range function.
=> Use date_range to get rid of FutureWarnings from pandas

src/gluonts/model/predictor.py
=> Respect num_eval_samples in predict method

requirements.txt, src/gluonts/core/component.py, src/gluonts/dataset/common.py, src/gluonts/model/forecast.py, src/gluonts/transform.py, test/core/test_component.py, test/distribution/test_distribution_inference.py
Fixes #107.
Between 0.12 (the last version we used) and 0.28, pydantic
* changed `get_validators` to `__get_validators__`
* prevents us from using the `fields` attribute on models
=> Updating pydantic to `0.28`.

.devtools/githooks/pre-commit, CONTRIBUTING.md, dev_setup.sh
=> remove flake8 from githook

ci/jenkins/build_steps.groovy
=> Disable warnings-as-failure for doc builds on master

src/gluonts/dataset/artificial/_base.py, test/dataset/artificial/test_complex_seasonal.py
When generating time series with ComplexSeasonalTimeSeries, if the range [min_val, max_val] isn't symmetric the time series are clipped. E.g. with the range [0, 10] all the negative values become 0 which is sometimes undesirable.
Adding the possibility to rescale the time series in the range [min_val, max_val].
=> Adding option to rescale time series instead of clipping them

test/paper_examples/test_axiv_paper_examples.py, test/paper_examples/test_paper_examples.py
Added paper code examples from the arxiv paper as tests. If these break, we need to update the arxiv paper code examples. One caveat is that the tests do not pull and run electricity because it takes too long. So if this line changes, the example would still break. But we should be able to catch a lot of other API changes this way. 
=> Added paper code examples as tests

.gitignore, docs/conf.py, requirements-setup.txt, setup.py, src/gluonts/__init__.py
Derive the verion used in `gluonts.__version__` automatically from the latest tag along the parent chain.
See https://pypi.org/project/setuptools-scm/ for details.
=> Use `setuptools_scm` to set the project version

.gitignore
*Description of changes:* A `version.py` file is created in `src/gluonts` which should not be edited nor committed: this PR adds it to the `.gitignore. Otherwise I think it's easy to stage this by mistake (especially when committing changes to many files).
=> ignoring version.py

setup.py
Fixes false negative caused by an uncaught Click error due to an API change between 6.* and 7.* versions.
=> Align the `StyleCheckCommand` with the click 7.* API

ci/jenkins/Jenkinsfile_py3-master_cpu_unittest, ci/jenkins/Jenkinsfile_py3_cpu_unittest, ci/jenkins/build_steps.groovy, setup.py
The checks are now performed by Jenkins.
=> Remove type- and style-checks from the build toolchain

src/gluonts/model/seq2seq/_mq_dnn_estimator.py
*Description of changes:* The `context_length` was not an optional parameter in `MQRNNEstimator` and `MQCNNEstimator`. This PR defaults it to `None`, in which case in the base class `MQDNNEstimator` it takes the same value as `prediction_length`.
=> fix default context_length in mqdnn

src/gluonts/model/forecast.py
Set the empty list as a default value of `samples` in all Forecast classes.
=> Set `samples` in `as_json_dict` for all Forecast classes

docs/examples/forecasting/tutorial.md, evaluations/generate_evaluations.py, examples/anomaly_detection.py, examples/benchmark_m4.py, examples/evaluate_model.py, examples/persist_model.py, src/gluonts/dataset/artificial/_base.py, src/gluonts/dataset/artificial/generate_synthetic.py, src/gluonts/dataset/common.py, src/gluonts/dataset/repository/_util.py, test/dataset/artificial/test_recipe.py, test/dataset/test_loader.py, test/model/test_backtest.py, test/model/test_deepar_auxiliary_outputs.py, test/model/test_models.py, test/model/test_models_synthetic.py, test/paper_examples/test_axiv_paper_examples.py
*Issue #, if available:* #134 
*Description of changes:* s/time_granularity/freq/g
**NOTE:** this is a breaking change.
=> time_granularity -> freq

src/gluonts/shell/sagemaker/__init__.py
---
Maybe we should check how the SageMaker `inputdataconfig.json` actually looks like.
=> More relaxed handling of inputdataconfig.

src/gluonts/shell/__main__.py, src/gluonts/shell/serve/__init__.py
When we use the dynamic forecaster, we don't require the `/opt/ml` path to exist.
=> Fixed path requirements for shell serve.

README.md, docs/examples/basic_forecasting_tutorial/tutorial.md, docs/examples/extended_forecasting_tutorial/extended_tutorial.md
Fixed readme links to the tutorials since we changed the paths and changed the tutorial titles to be consistent in the website.
=> fix readme links and tutorial titles

requirements/requirements.txt
Seems that GluonTS has an issue with the new MXNet version.
=> Exclude MXNet 1.5.* from allowed requirements

src/gluonts/dataset/repository/datasets.py, src/gluonts/model/testutil.py, src/gluonts/shell/__main__.py, src/gluonts/shell/serve.py, src/gluonts/shell/testutil.py, test/model/log.txt, test/model/test_backtest.py, test/model/test_predictor.py, test/shell/test_shell.py
Provides support for writing integration tests of predictors and estimators working within workflow of a SageMaker shell, as well as a test module that uses a dummy `MeanPredictor` in order to tests the shell itself. 
I tried to split this readable commits, but the main point of the PR is the third one (i.e., the `test_shell` test module and the utility functions in the `shell.testutil` module).
=> Shell test infrastructure

requirements/requirements.txt, src/gluonts/model/npts/_model.py, src/gluonts/transform.py
*Issue #, if available:* #177 
*Description of changes:* Pandas 0.25.0 was released, which fixes an issues with timestamp frequencies in the case of "W" and "M" frequency. This PR removes related workarounds. See [here](https://github.com/pandas-dev/pandas/blob/e95d2dd2201d67307ebc236a6006a3428b7eead8/pandas/tests/scalar/timestamp/test_arithmetic.py#L101-L130) for related tests in the 0.25.x branch.
=> Bump pandas version and remove timestamp workarounds

src/gluonts/shell/serve.py
Since SageMaker is sending out this request every 5 seconds, the logs get polluted with this info.
=> Removed logging for ping.

src/gluonts/model/deepar/_estimator.py, src/gluonts/model/deepar/_network.py, src/gluonts/model/gp_forecaster/_estimator.py, src/gluonts/model/npts/_predictor.py, src/gluonts/model/seq2seq/_seq2seq_estimator.py, src/gluonts/model/simple_feedforward/_estimator.py, src/gluonts/model/simple_feedforward/_network.py, src/gluonts/model/transformer/_estimator.py, src/gluonts/model/transformer/_network.py, src/gluonts/model/wavenet/_estimator.py, src/gluonts/model/wavenet/_network.py, test/model/test_models.py, test/model/test_models_synthetic.py, test/model/test_npts.py
With this PR I am trying to clear the ambiguity around `num_eval_samples`.
Currently, `num_eval_samples` can be defined in two places: In the estimator and in the `make_evaluation_predictions`. This is confusing to an external user since it is not clear what is the difference between these two, if one overwrites the other, or if they have a different usage.
The actual place that defines how many samples we get for prediction is `num_eval_samples` in the `make_evaluation_predictions`. We introduce `num_eval_samples` in an estimator just to increase the output dimension of the prediction network for computational efficiency. This suggests that we should distinguish between these two `num_eval_samples` hyperparameters. It also suggests that `num_eval_samples` in an estimator should be a bit …
=> Fix num_eval_samples

src/gluonts/model/predictor.py, src/gluonts/model/trivial/constant.py, src/gluonts/model/trivial/identity.py, src/gluonts/model/trivial/mean.py
Addresses #238.
Also added a way to create a MeanPredictor based on an existing Predictor.
=> Added `predict_item` to RepresentablePredictor and adapted subclasses.

src/gluonts/model/predictor.py
---
Not sure if catching all GluonTS errors is the right approach. However, one could argue that throwing a GluonTS error is deliberate and thus should be signaled to the user.
=> GluonTSException bypass fallback.

src/gluonts/model/canonical/_network.py, test/model/test_models.py
*Issue #, if available:* #161 
*Description of changes:* The time series scale tensor had some unnecessary additional axes in `CanonicalNetworkBase`, which resulted in wrong shapes (but no error) when `hybridize=False`, and in MXNet errors when `hybridize=True`. This PR hardens tests for *all* estimators by running with both `hybridize=False` and `hybridize=True`: this now clearly raises the problem with `CanonicalNetworkBase`-based estimators. Shapes are also fixed in `CanonicalNetworkBase`, and now tests pass.
*Bonus:* I uncommented a few test cases.
=> Fix shapes in CanonicalNetworkBase

src/gluonts/core/component.py, src/gluonts/model/predictor.py, src/gluonts/model/wavenet/_estimator.py, src/gluonts/model/wavenet/_network.py, src/gluonts/support/util.py, src/gluonts/trainer/_base.py
- introduce train_window_length to make convolutions more efficient during training
- make model hybridizable
- minor changes to mxnet utils (`get_mxnet_context` and `copy_parameters`)
=> Improvements for wavenet and some utils

src/gluonts/dataset/repository/_lstnet.py
=> fix pandas warnings in dataset generation

docs/examples/basic_forecasting_tutorial/tutorial.md, docs/examples/extended_forecasting_tutorial/extended_tutorial.md, src/gluonts/dataset/field_names.py, src/gluonts/dataset/stat.py, src/gluonts/model/canonical/_estimator.py, src/gluonts/model/deep_factor/_estimator.py, src/gluonts/model/deepar/_estimator.py, src/gluonts/model/deepstate/_estimator.py, src/gluonts/model/gp_forecaster/_estimator.py, src/gluonts/model/predictor.py, src/gluonts/model/seq2seq/_forking_estimator.py, src/gluonts/model/seq2seq/_seq2seq_estimator.py, src/gluonts/model/simple_feedforward/_estimator.py, src/gluonts/model/transformer/_estimator.py, src/gluonts/model/trivial/constant.py, src/gluonts/model/trivial/identity.py, src/gluonts/model/trivial/mean.py, src/gluonts/model/wavenet/_estimator.py, src/gluonts/transform.py, test/dataset/test_fieldnames.py, test/dataset/test_stat.py, test/model/seq2seq/test_forking_sequence_splitter.py, test/model/test_deepar_smoke.py, test/paper_examples/test_axiv_paper_examples.py, test/test_transform.py
The field names of a dataset are not checked for consistency across the different modules. If a field changes in the `FieldName` class, there is no error raised, the old fields are never there in the new datasets and therefore ignored, and the new fields are not processed.
This caused issue #283 in the dataset statistics calculation `dataset.calc_stats()`.
This PR includes the following changes:
- fixes the `calc_stats` issue (fixes issue #283 )
- moves the `FieldName` class to a separate module to avoid circular dependencies and to increase visibility for potential future changes (it was in the `transform` package with all the transformations and it did not really belong there)
- adds tests for potential change on the `FieldName` class so people are warned at least that they should not …
=> fixes fieldname issues

src/gluonts/model/wavenet/_network.py
*Issue #295 
Changed act_type by activation to be compliant with mxnet.gluon.nn.Activation syntax , see http://mxnet.incubator.apache.org/versions/1.4.1/api/python/gluon/nn.html#mxnet.gluon.nn.Activation
=> fixed bug when changing default activation function in wavenet #295

src/gluonts/core/serde.py, src/gluonts/distribution/bijection.py, src/gluonts/distribution/binned.py, src/gluonts/distribution/box_cox_tranform.py, src/gluonts/distribution/distribution_output.py, src/gluonts/distribution/gaussian.py, src/gluonts/distribution/laplace.py, src/gluonts/distribution/lds.py, src/gluonts/distribution/lowrank_multivariate_gaussian.py, src/gluonts/distribution/mixture.py, src/gluonts/distribution/multivariate_gaussian.py, src/gluonts/distribution/neg_binomial.py, src/gluonts/distribution/piecewise_linear.py, src/gluonts/distribution/student_t.py, src/gluonts/distribution/transformed_distribution.py, src/gluonts/distribution/transformed_distribution_output.py, src/gluonts/distribution/uniform.py, test/core/test_serde.py, test/distribution/test_distribution_inference.py, test/distribution/test_distribution_methods.py, test/distribution/test_distribution_sampling.py, test/distribution/test_distribution_shapes.py, test/distribution/test_mixture.py, test/distribution/test_piecewise_linear.py, test/distribution/test_transformed_distribution.py, test/model/test_models.py
This change makes mxnet tensors serializable with our `validated` mechanism and uses this to make all distributions serializable.
=> make tensors and distributions serializable

src/gluonts/distribution/box_cox_tranform.py, src/gluonts/distribution/distribution.py, src/gluonts/distribution/gaussian.py, src/gluonts/distribution/laplace.py, src/gluonts/distribution/piecewise_linear.py, src/gluonts/distribution/transformed_distribution.py, src/gluonts/distribution/uniform.py, src/gluonts/support/util.py, test/distribution/test_distribution_inference.py, test/distribution/test_distribution_sampling.py, test/distribution/test_distribution_shapes.py, test/distribution/test_piecewise_linear.py, test/distribution/test_transformed_distribution.py, test/support/test_util.py
Include a `quantile` function for distributions.
=> include quantile function in distribution

src/gluonts/dataset/artificial/_base.py, src/gluonts/dataset/artificial/recipe.py, test/dataset/artificial/test_recipe.py
=> More operators for synthetic data generation

src/gluonts/model/deepar/_estimator.py, src/gluonts/model/deepstate/_estimator.py
This is extra safeguard to make sure that `use_feat_static_cat` is explicitly set if  cardinality is set. I saw people leaving the defaults for `use_feat_static_cat` and believing the static features are used by deepar since they have set `cardinality`.
There is already issue/enhancement #144 opened to change the default behavior of setting `use_feat_static_cat=False`. We at least need the current fix until #144 is resolved. 
Currently it asserts one way implication:  `use_feat_static_cat=True` \implies `cardinality is not None`.
We need the converse as well: `cardinality is not None` \implies `use_feat_static_cat=True`.
=> Assert that static cat features are used in case cardinality is explicitly set

src/gluonts/model/deepar/_network.py
*Issue #, if available:* #303 
*Description of changes:* This fixes some bad reshaping of the samples generated in DeepAR. The issue does not affect the univariate case, but in the multivariate case it confuses the sample dimensions which result in the weird behaviour highlighted in #303.
=> Fix sample reshaping in DeepAR

src/gluonts/dataset/artificial/_base.py, src/gluonts/dataset/artificial/generate_synthetic.py
- Updating the artificial dataset module to use the default field names from `gluonts.dataset.field_names.FieldName` as requested in PR 321
- Prior each string was hard-coded
- More flexible for future design if the field strings are changed can be done all in `gluonts.dataset.field_names.FieldName`
=> Adding FieldNames to artificial dataset module

src/gluonts/model/deepar/_estimator.py, src/gluonts/model/deepar/_network.py
*Issue #, if available:* #309 
*Description of changes:* This adds the option to use the "feat_static_real" field with the DeepAREstimator. This can be useful to plug in any set of real-valued, time-independent features associated with the time series, including custom embeddings of text data.
I think that enabling this for *all* estimators is a good reason for having a general mechanism to synthesize the input transformation chain given the schema of the data, instead of having redundant copy-pasted-but-not-quite code all over the place. So I'm not doing this for all estimators in this PR.
*Bonus:* formatted a few docstrings better.
=> Add option for feat_static_real in DeepAREstimator

examples/gp_synthetic_example.py
- Added Gaussian Process (GP) synthetic example
- Shows how to call the `GaussianProcess` with the `exact_inference` and `plot` methods as well as how to select the kernel
- The plot shows the predictive mean and +/- 2 predictive stds
=> Adding GP example on synthetic dataset with built-in plotting

src/gluonts/model/forecast_generator.py, src/gluonts/model/forecast_wrapper.py, src/gluonts/model/predictor.py, src/gluonts/model/seq2seq/_forking_estimator.py, src/gluonts/model/seq2seq/_seq2seq_estimator.py
Make predictors and outputs more modular by introducing a `ForecastGenerator` that is used to bring the output of an mxnet block into a forecast.
=> Introduce ForecastGenerator to wrap mxnet output into forecast object

src/gluonts/distribution/__init__.py, src/gluonts/distribution/box_cox_tranform.py, src/gluonts/distribution/transformed_distribution_output.py
Some small fixes to boxcox:
- `lb_obs` was used with the wrong sign in boxcox. I.e. when the smallest observation is `-0.1` you had to set `lb_obs=0.1`
- fix broadcasting issue in the condition
=> Small fixes to box cox and `TransformedDistribution`

src/gluonts/core/component.py, src/gluonts/support/linalg_util.py, test/support/test_jitter.py
- Results in the error with Deep State described here https://github.com/awslabs/gluon-ts/issues/336
- Enabled gpu tests for the cholesky jitter iterative and eigenvalue methods for numerically non-positive definite matrices
- On the gpu, if the cholesky factor `L` is not positive definite, it stores `nan` in the entries rather than throwing an error like on the cpu
- Updated assert error on gpu that compares `L.nansum()` and `L.sum()` to remove incorrect end parenthesis and to add an additional absolute value due to numerical issues.
- Moved `test/gp/test_jitter.py` to `test/support/test_jitter.py` since the jitter methods are under `src/support/linalg_util.py`
By submitting this pull request, I confirm that you can use, modify, copy, …
=> Adding gpu support to the cholesky jitter and eig tests.

src/gluonts/trainer/learning_rate_scheduler.py
When the base learning rate is smaller than the minimum learning rate, the following operation is applied:
> max(min_lr, factor*base_lr)
This effectively increases the learning rate once the patience epochs without improvement are reached.
Description of changes:
I included an assert statement to break in case min_lr > base_lr
=> [Fix] Assure Learning Rate Scheduler does not increase the learning rate

src/gluonts/dataset/split/splitter.py
None
Fix typos in the documentation in `splitter.py`. The `DateSplitter` class does not have methods `split_dataset` and `rolling_split_dataset`; they should be `split` and `rolling_split`, respectively.
=> Fix typos in documentation

src/gluonts/shell/sagemaker/params.py
This PR allows to set custom classes as parameters for Estimators. E.g. it allows to set DistributionOutput to something other than StudentT for DeepAR.
```json
{
"forecaster_name": "gluonts.model.deepar.DeepAREstimator",
"distr_output": "{\"__kind__\": \"instance\",\"class\": \"gluonts.distribution.NegativeBinomialOutput\",\"args\": [],\"kwargs\": {}}"
}
=> Using custom SerDe methods for deserializing params in Sagemaker

test/distribution/test_distribution_sampling.py
*Description of changes:* There's one sampling test for StudentT that frequently fails. Hopefully this PR relaxes it enough, otherwise I'll further mark it with `@flaky`
=> fix flaky sampling test

test/distribution/test_distribution_sampling.py
Test was failing, because `np.allclose` failed.
=> Added flaky to test_sampling.

src/gluonts/trainer/_base.py
https://github.com/awslabs/gluon-ts/issues/310
This fixes the number of parameters. I need some education where I should best add a test for this or if I should indeed add a test for this. 
=> Fix printing of network parameters

dev_setup.sh, docs/community/devsetup.rst, setup.py
=> Simplified dev-setup.

src/gluonts/model/predictor.py
#278
This adds the version number of gluonts to the type.txt file during serialization, but doesn't do anything with this during deserialization. I tested this locally, but didn't add any unit tests. If I should, please point me to where I'd best do this.
=> address issue #278

src/gluonts/distribution/binned.py, src/gluonts/distribution/distribution.py, src/gluonts/distribution/gaussian.py, src/gluonts/distribution/laplace.py, src/gluonts/distribution/neg_binomial.py, src/gluonts/distribution/student_t.py, src/gluonts/distribution/uniform.py, test/distribution/test_distribution_slice.py
*Description of changes:* This allows to slice distributions across arbitrary axes, using the basically the same signatures as mx.nd.slice and mx.nd.slice_axis.
More tests/distributions to come, feedback wanted.
=> Add slice_axis methods to Distribution

src/gluonts/shell/serve/app.py, src/gluonts/testutil/shell.py
=> Batch transform debug

src/gluonts/model/r_forecast/_predictor.py
*Issue #, if available: None*
Changed the pip command from `pip install rpy2` to `pip install 'rpy2>=2.9.*,<3.*'`, which is consistent with [requirements-extras-r.txt](https://github.com/awslabs/gluon-ts/blob/master/requirements/requirements-extras-r.txt). The original command will install `rpy2` v3.2.1, which is not compatible with the `RForecastPredictor` class. 
=> Update the docstring of RForecastPredictor

src/gluonts/distribution/binned.py
The Binned distribution does not return the right batch shape since `bin_centers` is just a one-dimensional list common for all examples in the batch. The shape information is available in `bin_probs`.
=> Fix batch shape in Binned Distribution

src/gluonts/transform.py, test/test_transform.py
*Issue #367*
* Cause of issue #367: In `AddTimeFeatures`, when `time_features` or `self. date_features` is an empty list, the following snippet would throw an error.
```
self._full_range_date_features = np.vstack(
[feat(self.full_date_range) for feat in self.date_features]
)
```
* After this fix, if `time_features` is empty, `self._full_range_date_features` and `data[self.output_field]` will be set to `None`.
=> Fix empty time_features issue

examples/benchmark_m4.py
#376 
We currently do not use categorical feature in the evaluation of m4 datasets although this is present in the dataset. This often results in large error for `m4_hourly`. This PR adds cat feature  for the m4 evaluation. 
I ran deepar model with and without categorical feature. For `m4_hourly` there is a clear improvement. On other datasets using cat feature is slightly better for almost all datasets in terms of  `RMSE`, `mean_wQunatileLoss`, `MASE`. On the other metrics it is mixed although I think using cat in principle should always give better results; need to check the impact of `embedding_dim` on the performance.
**Without cat feature**
|dataset        |estimator         |RMSE  |mean_wQuantileLoss      |MASE|     sMAPE       |MSIS
| --- | --- | --- | ---  | --- | --- | --- | 
| …
=> Use static categorical feature for evaluating m4 datasets

src/gluonts/model/deepstate/_estimator.py, src/gluonts/testutil/dummy_datasets.py, test/model/test_deepstate_smoke.py
This PR tries to make sure that `DeepStateEstimator` is not misused :) The assumption is that `DeepStateEstimator` is usually applied to dataset of multiple time series that have at least one categorical feature (e.g., an *id* for each time series). This way comparison against classical state space models that fit a separate model to each time series in the dataset makes sense.
* Added missing smoke test for `DeepStateEstimator`.
* Added test to make sure that invalid settings with respect static categorical features raise exceptions.
=>  DeepStateEstimator: Make cardinality argument compulsory 

docs/examples/basic_forecasting_tutorial/tutorial.md, docs/examples/extended_forecasting_tutorial/extended_tutorial.md, src/gluonts/evaluation/backtest.py, src/gluonts/model/canonical/_estimator.py, src/gluonts/model/canonical/_network.py, src/gluonts/model/deep_factor/_estimator.py, src/gluonts/model/deep_factor/_network.py, src/gluonts/model/deepstate/_estimator.py, src/gluonts/model/deepstate/_network.py, src/gluonts/model/forecast.py, src/gluonts/model/forecast_generator.py, src/gluonts/model/gp_forecaster/_estimator.py, src/gluonts/model/gp_forecaster/_network.py, src/gluonts/model/npts/_predictor.py, src/gluonts/model/predictor.py, src/gluonts/model/prophet/_predictor.py, src/gluonts/model/r_forecast/_predictor.py, src/gluonts/model/trivial/constant.py, src/gluonts/model/trivial/mean.py, src/gluonts/shell/serve/app.py, src/gluonts/shell/train.py, test/model/test_backtest.py, test/model/test_models.py, test/model/test_npts.py, test/model/test_predictor.py, test/shell/test_shell.py
Fixes issue #301 (following #232).
=> num_sample variation fixes

src/gluonts/distribution/lds.py, src/gluonts/model/deepstate/_estimator.py, test/model/test_models.py
*Issue #, if available:* fixes #437 
*Description of changes:* fixes DeepState serialization, adds tests.
=> fix deepstate serialization, add tests

requirements/requirements.txt
This allows gluon-ts to be installed in a project that requires
similar dependencies. Because gluon-ts dependencies constraints
are too strict, it may prevent it from being installed side by
side with those other libraries if the constraints cannot resolve
to a common version.
=> Relax requirements constraints

test/distribution/test_mixture.py
`normed` is deprecated in favour of `density`.
=> Fix use of numpy.histogram.

src/gluonts/distribution/transformed_distribution_output.py
#463 
While testing Box Cox transformation I found that there is a validation error that needs a fi.x
I was able to train a `DeepAR` model after fixing this by specifying the distribution output as
```
distr_output=distribution.TransformedDistributionOutput(
distribution.GaussianOutput(), [distribution.InverseBoxCoxTransformOutput(lb_obs=-1.0E-5)]
)
```
=> fix validation error in transformed distribution output

src/gluonts/model/deepvar/__init__.py, src/gluonts/model/deepvar/_estimator.py, src/gluonts/model/deepvar/_network.py, src/gluonts/support/util.py, src/gluonts/transform.py, test/model/test_deepvar.py, test/test_transform.py
Introduces the DeepVAR model for multivariate forecasts. This is the basic abstraction leading up to the GP Copula model (which comes in the next PR). 
=> Introduces DeepVAR model

src/gluonts/dataset/field_names.py, src/gluonts/distribution/lowrank_gp.py, src/gluonts/distribution/lowrank_multivariate_gaussian.py, src/gluonts/model/deepvar/_estimator.py, src/gluonts/model/deepvar/_network.py, src/gluonts/model/gpvar/__init__.py, src/gluonts/model/gpvar/_estimator.py, src/gluonts/model/gpvar/_network.py, src/gluonts/transform.py, test/distribution/test_distribution_inference.py, test/model/test_gpvar.py
Adds the GP-Copula model from this paper: https://arxiv.org/abs/1910.03002. 
I had to reverse some refactorings for the `DeepVAR` model (which is the base class for `GPVAR`. I also had to play a bit with the inference test because of the changes the lowrank multivariate distribution that we introduced to avoid cholesky problems.  
=> Add GP-Copula model.

src/gluonts/transform.py, test/test_transform.py
This is the first PR setting up the infrastructure for temporal point processes in GluonTS (#294). 
Put simply it introduces the `ContinuousTimeInstanceSplitter` object, which somewhat replicates the logic of an `InstanceSplitter` for but for point processes in continuous time. I thought this was a good first PR for me, and a good place to start the process of bringing in TPPs.
=> Add transform objects for temporal point processes (#294)

src/gluonts/dataset/common.py
Currently, we throw an error if we encounter tz-information in a start-field.
The idea is to have different strategies dealing with such time-information:
* error -- current behaviour
* utc -- get time in UTC, e.g. if time zone is eastern time, we add 5 hours to the time and then remove the tz information
* ignore -- removes the timezone information
Maybe we could use `global` for `utc` and `local` for `ignore` instead.
=> Added strategies for timezone information.

src/gluonts/transform/_base.py
Makes it easier to use multiple transformations.
```python
chain = SetField("foo", 42) + SetField("bar", 99)
```
We could think about using a different operator than `+`, but `+` is probably most fitting.
=> Added operator to allow for easier chaining of transformations.

src/gluonts/transform/sampler.py, src/gluonts/transform/split.py, test/test_transform.py
*Description of changes:* Some checks are added in the `InstanceSplitter` class for the case where `pick_incomplete=False`. This would otherwise cause problems downstream, when the sampler would to sample from an interval that has inverted bounds.
Further checks and typing cleanup are added.
Opening for feedback, trying to include a small test for this.
=> Fix instance splitter issue with short time series

src/gluonts/distribution/binned.py, test/distribution/test_distribution_sampling.py
*Issue #535:*
Looks like `zeros_batch_size` is also mainly to get the shape right. It is used [here](https://github.com/awslabs/gluon-ts/blob/a9cde7bf92178b4cf8010a4c8600940b595f2ae3/src/gluonts/distribution/binned.py#L147) just as a placeholder. Made this zero and `zeros_cdf` also becomes zero with that.
Updated tests as well.
=> Fix #535: quantile of Binned distribution

src/gluonts/dataset/common.py
Source context's source is the path rather than the whole tuple.
=> Fixed FileDataset SourceContext

src/gluonts/distribution/transformed_distribution.py, src/gluonts/model/forecast.py
Fix quantile function for transformed distribution and minor other improvements.
This reduces memory consumption when calculating quantiles for transformed distribution.
Also minor improvements for forecast methods.
=> fix quantile fn for transformed distribution

src/gluonts/distribution/bijection.py, src/gluonts/distribution/binned.py, src/gluonts/distribution/dirichlet.py, src/gluonts/distribution/dirichlet_multinomial.py, src/gluonts/distribution/distribution_output.py, src/gluonts/distribution/lowrank_gp.py, src/gluonts/distribution/lowrank_multivariate_gaussian.py, src/gluonts/distribution/mixture.py, src/gluonts/distribution/neg_binomial.py, src/gluonts/distribution/piecewise_linear.py, src/gluonts/distribution/transformed_distribution_output.py, test/distribution/test_distribution_output_shapes.py
*Description of changes:* This PR adds the `loc` argument to the `distribution` method of `DistributionOutput` classes. Assertions are added in case the specific distributions don't support either `loc` or `scale`. A bug in the `TransformedPiecewiseLinear` distribution was also fixed: this went unnoticed since it only appears when the base distribution is composed with more than one affine transformation, which never happens when using `PiecewiseLinearOutput`.
=> Add `loc` argument to distribution output classes

src/gluonts/distribution/__init__.py, src/gluonts/distribution/poisson.py, test/distribution/test_distribution_inference.py, test/distribution/test_distribution_methods.py, test/distribution/test_distribution_output_shapes.py, test/distribution/test_distribution_sampling.py, test/distribution/test_distribution_shapes.py
*Issue #, if available:* fixes #529
Implement poisson distribution based on scipy.stats.poisson, Please correct me if there is any mistakes!
Also I can't seem to find a way to set all 0 to 1 in the x tensor for log_prob method, as the x seem to change to symbol object as training went on.
=> add poisson distribution

src/gluonts/distribution/binned.py, test/distribution/test_distribution_inference.py, test/distribution/test_distribution_methods.py, test/distribution/test_distribution_sampling.py
Co-authored with @canerturkmen 
*Description of changes:* The Binned distribution is not too robust in its `log_prob` method. The reason is the internal representation being based on the probabilities of the bins, rather than directly the log probabilities. This can be seen with the following MWE:
```python
import mxnet as mx
from gluonts.distribution import BinnedOutput
distr_out = BinnedOutput(bin_centers=mx.nd.array([1.0, 2.0, 3.0, 4.0, 5.0]))
args_proj = distr_out.get_args_proj()
args_proj.initialize()
network_out = 50*mx.nd.ones(shape=(10,))
args = args_proj(network_out)
distr = distr_out.distribution(args=args)
print(distr.log_prob(mx.nd.array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5])))
```
Output **before** the fix:
```python
[nan nan nan nan nan nan]
<NDArray 6 @cpu(0)>
```
Output **after** …
=> Representing the Binned distribution directly through log probabilities

src/gluonts/dataset/common.py, src/gluonts/evaluation/backtest.py, src/gluonts/model/trivial/mean.py, src/gluonts/shell/train.py, src/gluonts/support/util.py
*Description of changes:* This removes the `Dataset` class in favor of a type alias, allowing e.g. to just use a list with the appropriate fields as dataset.
```python
train_data = [
"start": pd.Timestamp(...),
"target": np.array([...])
]
```
=> Remove Dataset class in favor of type alias

src/gluonts/distribution/piecewise_linear.py, test/distribution/test_piecewise_linear.py
*Issue #, if available:* partially addressing #563 
*Description of changes:* This fixes a bug in the cdf method of PiecewiseLinear, which was returning values larger than 1.0: this addresses the simpler example in #563. The more complex example there has to do with numerical problems, which make the cdf evaluation fail there, and crps as well as a consequence I believe. That problem will need more care.
=> Fix bug in cdf method of piecewise linear distributions

src/gluonts/dataset/repository/_gp_copula_2019.py, src/gluonts/dataset/repository/_lstnet.py, src/gluonts/dataset/repository/_m4.py, src/gluonts/dataset/repository/_util.py
*Issue #, if available:* #291 
*Description of changes:* This adds an `"item_id"` field in the provided dataset recipes. Getting the datases with `regenerate=True` should then fix #291. I set the `"item_id"` field to be the same incremental integer as the `"cat"` field, but we could decide of using something slightly different there for clarity (like the `"item<N>"` string or something like that).
=> Fix item_id field in provided datasets

docs/examples/synthetic_data_generation_tutorial/tutorial.md
*Description of changes:* I believe the scale was being generated with the wrong shape in one of the examples, this fixes it by making it uniform in time
=> Fix scale in synthetic data generation tutorial

src/gluonts/dataset/common.py, test/model/test_npts.py
=> Removed expand_dims when reading in time-series values.

src/gluonts/support/util.py, test/support/test_util.py
*Issue #, if available:* #581 
Changes symbol block import/export helpers in `support.util` to persist input/output format information and tiptoes around some other mxnet quirks.
=> Fix for symbol block serialization issue

src/gluonts/block/cnn.py
Default activation used in [CausalConv1d](https://gluon-ts.mxnet.io/api/gluonts/gluonts.block.cnn.html#) doesn't match the code. Changing it to`None` from `"relu"`.
=> Change causal conv1d default activation to match the doc

src/gluonts/support/util.py, test/support/test_util.py
*Issue #, if available:* #589
Just falls back to business as usual if the format json file is not where it's supposed to be, ensuring that previously persisted models can still be imported without a `FileNotFoundError`. 
Also, added the mxnet issue reference since we'll eventually have to get rid of this when mxnet starts handling it. 
Thanks @lostella  for pointing this out so quickly.
=> fix for symbol block import backward compatibility

src/gluonts/model/n_beats/_ensemble.py, src/gluonts/model/n_beats/_estimator.py, src/gluonts/model/n_beats/_network.py
I found that the trend block expansion_coefficient_lengths default is off by one when compared to the paper. I checked again, and the paper doesn't specify the dimension of expansion_coefficient_lengths for the generic block. Before it was the same as for the trend block, however, I think it makes sense to increase it to 32, since for example the seasonality block has horizon/2 number of coefficients, so its reasonable to give the generic block more possibilities to learn a larger generic basis.
The changes marginally improve performance in some cases.
=> Updated N-Beats defaults.

src/gluonts/model/n_beats/_network.py
Using the sMAPE function in conjunction with a trainer with a learning rate above 1e-4 lead to the models not converging/ learning at all in many cases (i.e. different datasets and different model instantiation like generic vs interpretable etc.).
This is now fixed by stopping gradient flow in the denominator of sMAPE.
=> Fixed sMAPE related learning issues.

src/gluonts/model/forecast.py
*Issue #, if available:* fixes #623 
=> fix mean_ts method

src/gluonts/model/forecast.py
Some classes were too liberal with type annotations, with the side effect that IDE hints show no types, slowing down using such classes.
=> Fix some mypy issues and add type annotations in forecast.py

src/gluonts/transform/sampler.py
=> Refactored instance sampler.

src/gluonts/model/predictor.py
*Issue #, if available:* The `as_symbol_block_predictor` method returns a predictor with a network that is on the wrong context. This is apparent when the original predictor was trained on GPU.
See the following minimal example:
```python
import pandas as pd
import numpy as np
import mxnet as mx
from gluonts.model.simple_feedforward import SimpleFeedForwardEstimator
from gluonts.trainer import Trainer
from gluonts.dataset.loader import InferenceDataLoader
estimator = SimpleFeedForwardEstimator(
prediction_length=24,
freq="1H",
trainer=Trainer(num_batches_per_epoch=1, epochs=1, hybridize=True, ctx=mx.gpu())
)
dataset = [
{"start": pd.Timestamp("2020-01-01", freq="1H"), "target": np.array([0.0]*500)}
]
predictor = estimator.train(dataset)
inference_data_loader = InferenceDataLoader( …
```
=> fixing context when converting to symbol block predictor

env/cpu/py3-master.yml, env/cpu/py3.yml, env/gpu/py3-master.yml, env/gpu/py3.yml
*Issue, if available:*
Jenkins was not able to resolve the numpy dependency all along (it had 1.18 and 1.14 both installed in some weird way, one through anaconda and one through pip), but apparently it did not have a noticeable impact so far, and only lead in https://github.com/awslabs/gluon-ts/pull/602 to complications.
* updating yaml dependencies
* in particular adding numpy explicitly
=> Aligning jenkins dependencies with requirement files.

env/cpu/py3-master.yml, env/cpu/py3.yml, env/gpu/py3-master.yml, env/gpu/py3.yml
*Issue, if available:*
Because we moved correctly the `numpy` dependency to the conda env directly, we had an additional `mkl` version installed within anaconda, additionally to the `mkl` version that came from the `mxnet_mkl` version. Anaconda once again was not able to resolve this. This lead to one of the jenkins builds timing out.
* Changed `mxnet_mkl` to `mxnet`.
* Some minor dependency improvements
=> Fixing mkl dependency issue, and further improvements.

src/gluonts/dataset/loader.py, test/model/test_deepar_auxiliary_outputs.py
Last refactoring broke the `DataLoader`'s ability to loop over the data multiple times.
This gives problems when using the validation channel for more than one epoch.
=> fix data loader and include validation channel in test

src/gluonts/model/lstnet/__init__.py, src/gluonts/model/lstnet/_estimator.py, src/gluonts/model/lstnet/_network.py, test/model/test_lstnet.py
An implemetation of [LSTNet](https://arxiv.org/abs/1703.07015).
_Note that I haven't replicated all of the paper's results as there is quite a big range of hyper-parameters that paper used for tuning and no final hyper-parameters were given!_
TODO: Temporal Attention layer.
=> Add LSTNet

src/gluonts/dataset/repository/_m5.py, src/gluonts/dataset/repository/_util.py, src/gluonts/dataset/repository/datasets.py
Following our notebooks for the the M5 accuracy and uncertainty forecasting competitions, this PR now adds a convenience data loading method for the M5 data. This method will load the Kaggle data and add the relevant static and dynamic features. Unfortunately, since the data is only available once users agree to the terms and conditions on Kaggle, we have to ask the user to supply the data to us which we can then process into a GluonTS-readable format. A respective runtime error will alert the user to first download the data from Kaggle and paste the data into our dataset directory in case these files are not present.
=> M5 data loader

src/gluonts/distribution/binned.py
For some reason using `*` and `+` instead of the verbose `broadcast_mul` and `broadcast_add` with hybridize gives wrong results on mxnet 1.6 on a GPU for the binned distribution. I think it only occurs when using `get_constant`. I'm filing a bug report for mxnet for this.
=> fix binned distribution for mxnet 1.6

src/gluonts/distribution/dirichlet.py, src/gluonts/distribution/dirichlet_multinomial.py, src/gluonts/distribution/neg_binomial.py, src/gluonts/distribution/poisson.py
*Issue #, if available:* fixes #641 
*Description of changes:* For some distributions, it doesn't make sense to prescribe a "loc" or "scale" by which to translate and scale the distribution arguments. However, networks that do compute a location/scale for the (past) data (and potentially use them to scale the network inputs) may provide this information to the DistributionOutput class when invoking the `distribution` method: in these cases, we currently raise an exception. This is not ideal, because it means that you cannot excange a distribution family that does support loc/scale for one that doesn't, on top of the same network. I think the best solution is to simply ignore loc and scale in DistributionOutput classes that don't support them.
By submitting this pull request, I confirm …
=> Remove asserts on loc and scale in distributions that do not support them

docs/bibliography.rst, src/gluonts/distribution/binned.py, test/distribution/test_distribution_methods.py, test/distribution/test_distribution_sampling.py, test/distribution/test_label_smoothing.py
Introduces a version of the `Binned` distribution that features [label smoothing](https://arxiv.org/abs/1906.02629), a technique formerly found to promote better calibration, faster training, and better generalization with binned type losses.
The implementation subclasses `Binned` and `BinnedOutput`, overriding the `loss()` method of the former. Edits to `binned.py` are to prevent code duplication.
=> Label smoothing binned distribution

src/gluonts/model/wavenet/_estimator.py, src/gluonts/model/wavenet/_network.py
This PR refactors the wavenet model in particular the network by moving out the common code used by both training and prediction networks. 
Running `benchmark.py` to make sure there is no regression. Initial result on `m4_hourly` dataset looks okay.
=> Refactor wavenet model

requirements/requirements.txt
=> Remove direct python-dateutil dependency.

requirements/requirements.txt
*Description of changes:* Making the requirement on numpy a superset of the one imposed by mxnet 1.6.0 (see https://github.com/apache/incubator-mxnet/blob/1.6.0/python/setup.py#L33).
This may be needed in environments that come with pre-packaged mxnet 1.6.0 and a minimal requirement on numpy and no easy way to update it.
=> Relax numpy requirement

src/gluonts/dataset/parallelized_loader.py, src/gluonts/evaluation/_base.py, src/gluonts/support/util.py
*Description of changes:* Apparently `time.clock()` and `from collection import <some-ABC>` are deprecated and removed in Python 3.8 and 3.9 respectively. Fixing their usage since they pollute the logs with warnings.
=> Remove deprecated features

src/gluonts/core/component.py
Fixes #767
The `model_name` argument was renamed to `__model_name` in
[1367](https://github.com/samuelcolvin/pydantic/pull/1367).
This change ensure that our code works with both future and past
versions of pydantic.
=> Fix pydanitc `create_model` usage.

test/dataset/test_loader.py, test/model/wavenet/test_model.py
*Issue #, if available:* Related to #774, #772, #727, 
*Description of changes:* A test introduced in #727 times out on windows, we need to check why that's the case but for now we can skip it so that the build is green and does not hide other issues on windows.
=> Skip WaveNet test on windows

src/gluonts/core/component.py
This backports #768 onto the v0.4.x branch.
=> Backport #768: Fix pydanitc `create_model` usage.

src/gluonts/dataset/parallelized_loader.py, test/dataset/test_variable_length.py
*Issue #, if available:* Related to #294 
Currently data loaders assume that arrays (e.g., that come out of a splitter type transform) are easily stackable into data batches. This is not convenient when working with time series of variable length that a model may want to see, such as when working with temporal point processes.
Here, we add variable-length awareness to the `batchify` and `stack` functions in the parallelized loader. We also expose the batchify function as a constructor argument to `ParallelDataLoader`. A consumer of DataLoaders can now specify `DataLoader(..., variable_length=True)` in order to make the loader aware that some input fields may not be stackable. In this case, the loader pads the arrays on the right along the first dimension (this is …
=> Add variable length functionality to DataLoaders

src/gluonts/dataset/common.py, src/gluonts/dataset/jsonl.py, src/gluonts/dataset/loader.py, src/gluonts/dataset/parallelized_loader.py, src/gluonts/dataset/util.py, test/dataset/test_multiprocessing_loader.py
Fixes a bug, where we keep iterating over the same data with each epoch instead of continuing from the last point. Also some minor improvements to the `ListDataset`.
FYI, this bug was introduced a few month ago (before the parallel data loader), so training with longer datasets has since then only used the first `num_batches_per_epoch x batch_size` entries.
=> fix bug with iteration over datasets

test/dataset/test_multiprocessing_loader.py
*Description of changes:* one of the multiprocessing data loader tests is flaky and will likely block PRs going ahead; declaring it flaky. Note that this test is inherently noisy at the moment, since it’s hard to guarantee that workers goes through their respective subsets of the data the same number of times. In order to guarantee that, we would need to change the way batches are pulled out of the workers outputs 
=> Make data loader test flaky

src/gluonts/block/scaler.py, test/block/test_scaler.py
fixed the scaler to work on time first and time last shaped tensors.
#765 
The scaler now takes axis argument to specify the axis over which to calculate the scaling.
=> Scaler for (N,T,C) and (N,C,T) tensors

src/gluonts/evaluation/backtest.py, src/gluonts/model/estimator.py, src/gluonts/model/lstnet/_estimator.py, src/gluonts/model/lstnet/_network.py, src/gluonts/model/n_beats/_ensemble.py, src/gluonts/model/naive_2/_predictor.py, src/gluonts/model/npts/_predictor.py, src/gluonts/model/predictor.py, src/gluonts/model/prophet/_predictor.py, src/gluonts/model/r_forecast/_predictor.py, src/gluonts/model/seasonal_naive/_predictor.py, src/gluonts/model/trivial/constant.py, src/gluonts/model/trivial/identity.py, src/gluonts/model/trivial/mean.py, src/gluonts/transform/split.py, test/model/lstnet/test_lstnet.py, test/test_transform.py
*Issue #, if available:* #677 
*Description of changes:* This PR adds a lead_time attribute to both predictor and estimators, and modifies the InstanceSplitter class to take into account for lead_time. By default, lead_time is everywhere 0, so existing predictors and estimators are backwards compatible (provided that they invoke the super constructor upon construction).
Some evaluation code needed to be adjusted, and the LSTNet implementation was also updated accordingly (and simplified in some aspects).
=> Add lead_time to predictors and estimators, update LSTNet

src/gluonts/model/r_forecast/_predictor.py
fix pandas Timestamp
the pandas API has changed and this is the preferred way as far as i am aware.
=> fix in RForecastPredictor

src/gluonts/model/lstnet/_estimator.py, src/gluonts/model/lstnet/_network.py, test/model/lstnet/test_lstnet.py
We need to use a Conv2D with appropriate kernel size
We now use the appropriate scaling and the loss takes it into account, and more importantly the Convolution has to be 2D with kernel size ` (num_series, kernel_size)`. 
We also need the hidden sizes of the two RNNs to be specified as they are not `channels`. 
I will debug the method shortly, but hopefully this describes the issues with the current implementation.
=> LSTNet fixes

src/gluonts/model/lstnet/_network.py, test/model/lstnet/test_lstnet.py
*Issue #, if available:* Addresses the same issue as #802 
*Description of changes:* This PR addresses the same issue as #802 (issues with scaling=False and hybridize=True) by
* using the observed indicator as input to the model blocks (CNN and FF)
Furthermore
* future observed indicator is added to the training network and used to mask the loss
* tests updates are copied from #802, except that the number of test cases is here reduced
cc @ehsanmok 
=> Fix LSTNet observed indicator usage

src/gluonts/gluonts_tqdm.py, src/gluonts/shell/__main__.py
When running on SageMaker, the logs get botched like this:
```
[2020-05-06 19:37:08] [INFO] gluonts.trainer Epoch[1] Learning rate is 0.001
#015  0%|          | 0/250 [00:00<?, ?it/s]#015 61%|██████    | 153/250 [00:10<00:06, 15.20it/s, epoch=2/250, avg_epoch_loss=21.7]#015100%|██████████| 250/250 [00:16<00:00, 15.24it/s, epoch=2/250, avg_epoch_loss=20.7]
[2020-05-06 19:37:25] [INFO] gluonts.trainer Epoch[1] Elapsed time 16.403 seconds
```
By checking for [`TRAINING_JOB_NAME`](https://docs.aws.amazon.com/sagemaker/latest/dg/your-algorithms-training-algo-running-container.html) we can test whether we are running on SageMaker and just turn the progress bar off.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of …
=> Disable TQDM when running on SageMaker.

src/gluonts/distribution/__init__.py, src/gluonts/distribution/logit_normal.py, test/distribution/test_distribution_inference.py
This PR adds the [logit-normal distribution](https://en.wikipedia.org/wiki/Logit-normal_distribution). This distribution is useful for probability-integral-transformed inputs. While the marginal distribution over probability-integral-transformed data is uniform, the conditional distribution is not and that's where this distribution (and especially a mixture) gives us more flexibility to model data lying in (0,1). Since there are no analytic solutions for the mean and the variance of this distribution, the corresponding tests requiring these properties were omitted.
=> Add logit normal distribution

src/gluonts/distribution/neg_binomial.py
*Issue #, if available:* #718 #719 and may be related to #636 
*Description of changes:* The scaling of `alpha` in #719 only makes sense if `scale >= 1.0`, otherwise the scaled `alpha` can become negative. Intuitively this makes a lot of sense for count data, which can only really be upscaled and not downscaled.
This PR makes sure that that's the case. Essentially, if `scale < 1.0` then it is set to `1.0`.
As a minimum working example, consider the following snippet:
```python
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from gluonts.model.simple_feedforward import SimpleFeedForwardEstimator
from gluonts.distribution import NegativeBinomialOutput
from gluonts.dataset.common import ListDataset
from gluonts.trainer import Trainer
data = …
```
=> Fix NegativeBinomial scaling

src/gluonts/model/predictor.py, src/gluonts/model/tpp/__init__.py, src/gluonts/model/tpp/forecast.py, src/gluonts/model/tpp/predictor.py, src/gluonts/transform/__init__.py, test/model/tpp/__init__.py, test/model/tpp/common.py, test/model/tpp/test_tpp_predictor.py
*Issue #, if available:* Related to  #294
*Description of changes:* Adds `SampleForecast`, `ForecastGenerator` and `GluonPredictor` objects that will be shared among temporal point process models. TPPs need unique subclasses of each primarily since forecasts need to be ragged tensors (variable valid length) and predictors must be aware of unique inference data loaders / forecast generators.
=> add SampleForecast and Predictor objects for TPPs

src/gluonts/distribution/categorical.py
This PR adds an optional constructor parameter `temperature` to `CategoricalOutput` to enable temperature scaling in the categorical distribution.
=> Add temperature scaling to categorical distribution

test/model/gp_forecaster/test_model.py, test/model/seq2seq/test_model.py
*Description of changes:* Tests for MQRNNEstimator and GaussianProcessEstimator fail consistently on Jenkins. Raising the thresholds since this is annoying (and these tests should really be used as smoke tests primarily)
=> Raise test thresholds for MQRNN and GaussianProcess

src/gluonts/support/util.py
*Issue #, if available:* N/A
GluonTS networks inherit from HybridBlocks whose `hybrid_forward` methods have arguments `(F, x1, x2,..., **kwargs)`. Our models exclude `**kwargs` when overriding and often suppress the IDE inspection with `#noinspection PyMethodOverriding`. 
The reason that this doesn't cause any problems is that GluonTS networks often do not have any parameters in their name scope, which would be passed into the `hybrid_forward` method as keyword arguments. 
When a GluonTS network does include `**kwargs` in the signature then `get_hybrid_forward_input_names` fails as it includes `"kwargs"` in `input_names`. 
This small fix removes special arguments in the `hybrid_forward` signature (*, *args, **kwargs) when inferring input names.
By submitting this …
=> remove kwargs from hybrid_forward input name inference

src/gluonts/evaluation/_base.py
*Issue #, if available:* Fixes #848 
*Description of changes:* The quantiles used for computing MSIS were not really controlled by the alpha parameter of the Evaluator class, despite what the documentations says. This PR tries to fix that and make them entirely dependent on alpha.
=> Fix the quantiles used to compute MSIS

src/gluonts/core/component.py
=> Fix comparison of ParameterDict when non prefixed variables are in dict.

examples/gp_synthetic_example.py, test/dataset/test_multiprocessing_loader.py, test/kernels/test_periodic_kernel.py, test/kernels/test_rbf_kernel.py, test/model/gp_forecaster/test_inference.py, test/representation/test_bin.py, test/representation/test_grb.py, test/representation/test_hyb.py, test/representation/test_lab.py, test/representation/test_mean.py, test/representation/test_rep.py, test/support/test_jitter.py, test/trainer/test_trainer.py
*Description of changes:* Fixing import following #876 
=> fix imports

src/gluonts/dataset/loader.py, src/gluonts/dataset/parallelized_loader.py, src/gluonts/model/estimator.py, test/dataset/test_shuffling.py
*Note: replaces #858*
Added ShuffleIter class to enable shuffling  in data loader.
In the first time comparison plot, the x-axis represents the shuffle buffer length, that is, if the x-axis is c, then the shuffle buffer is of size c * batch size, y-axis is the time used to generate 200 batches of size 32 from a dataset of length 300.
In the following heatmaps, x-axis is the batch index, y-axis is the time series index, and color intensity indicates how many elements in the x-batch are from the y-time-series
=> Add shuffling function

src/gluonts/mx/distribution/beta.py, src/gluonts/mx/distribution/binned.py, src/gluonts/mx/distribution/categorical.py, src/gluonts/mx/distribution/dirichlet.py, src/gluonts/mx/distribution/dirichlet_multinomial.py, src/gluonts/mx/distribution/gamma.py, src/gluonts/mx/distribution/gaussian.py, src/gluonts/mx/distribution/laplace.py, src/gluonts/mx/distribution/lds.py, src/gluonts/mx/distribution/logit_normal.py, src/gluonts/mx/distribution/lowrank_multivariate_gaussian.py, src/gluonts/mx/distribution/mixture.py, src/gluonts/mx/distribution/multivariate_gaussian.py, src/gluonts/mx/distribution/neg_binomial.py, src/gluonts/mx/distribution/piecewise_linear.py, src/gluonts/mx/distribution/poisson.py, src/gluonts/mx/distribution/student_t.py, src/gluonts/mx/distribution/uniform.py
*Issue #, if available:* Related to #870 
*Description of changes:* Many if not all of the distribution classes are not pickle-able because they have a module (`F`, either `mx.nd` or `mx.sym`) as attribute. This create problems if one needs to do multi-processing things involving distributions (like parallel evaluation).
Having `F` as an attribute seems like unnecessary optimization, since the `getF` utility function is inexpensive. Therefore I'm turning `self.F` into a `@property` that invokes `getF`.
=> make distributions pickleable

src/gluonts/dataset/parallelized_loader.py
* There was a possibility of manually setting more workers than there are time series in the dataset, which currently is not supported.
=> Fixed invalid num_worker possibility.

src/gluonts/dataset/split/splitter.py, test/dataset/split/test_split.py
*Description of changes:* 
Enabled splitters to split features as well as the target for datasets. Also converted Splitters to intake and output type DataEntry instead of TimeSeriesItem, so that it is standard with the rest of the gluon-ts library.
=> splitting features and uses DataEntry instead of TimeSeriesItem

src/gluonts/transform/feature.py, test/test_transform.py
Small refactoring of `AddObservedValueIndicator` transformation. 
Removed unnecessary fields:
- `dummy_value`: This is imputation-method-dependent and should not be an argument of the transformation. Instead the transformation should take as input the imputation method with this field set already.
- `convert_nans`: This is unnecessary since we can just use None as imputation method.
With the above change we have control **IF** we want to do imputation or not in the transformation by including a hyperparameter in the estimator (setting it to the appropriate imputation method or to None). This gives the flexibility to select from a model-based imputation method (e.g. if set to None use a sample from the predictive distribution since the imputation from the transformation is disabled) or …
=> refactor imputation transformation

src/gluonts/dataset/loader.py, src/gluonts/dataset/parallelized_loader.py, src/gluonts/model/wavenet/_estimator.py, test/trainer/test_learning_rate_scheduler.py, test/trainer/test_model_averaging.py
In this PR, documentations are added related to ```shuffle_buffer_length``` in ```loader.py``` and ```parallelized_loader.py```.
And minor bugs are fixed where shuffle_buffer_length is taken as an implicit input in some model that reimplement train method in ```GluonEstimator```. Current I only find wavenet does this.
=> Improve shuffle function

src/gluonts/mx/distribution/neg_binomial.py
For issue #906 
The `theta` param. of Gamma gets scaled by `scale *theta = alpha * mu * scale`. So only need to scale the `mu` . See: https://en.wikipedia.org/wiki/Gamma_distribution#Scaling
=> Scale the negative binomial's gamma()

src/gluonts/transform/feature.py, test/test_transform.py
Fixes an edge case where we pass a single value and `np.squeeze` suppresses all dimensions.
=> Shape squeeze edge case bug fix

src/gluonts/dataset/field_names.py, src/gluonts/dataset/stat.py, src/gluonts/model/seq2seq/_forking_estimator.py, src/gluonts/model/seq2seq/_forking_network.py, src/gluonts/model/seq2seq/_mq_dnn_estimator.py, src/gluonts/model/seq2seq/_seq2seq_estimator.py, src/gluonts/model/seq2seq/_transform.py, src/gluonts/testutil/dummy_datasets.py, src/gluonts/transform/convert.py, test/dataset/test_stat.py, test/model/seq2seq/test_model.py
- Added support for past dynamic features with `use_past_feat_dynamic_real` boolean.
- Added scaling for dynamic features for the decoder using `scaling_decoder_dynamic_feature` and set default target `scaling = False`
- Enabled dynamic features to be used in only the encoder, only the decoder and both using the booleans `enable_encoder_dynamic_feature` and `enable_decoder_dynamic_feature`
- Updated default parameter values: set `add_time_feature` default to `True`
- Updated default `dilation_seq = [1, 3, 9]`, since that minimized the variance in the experiments
=> MQCNN: Support for past dynamic features and scaling

src/gluonts/shell/serve/app.py
`.splitlines()` also splits on `\u2028`, which is not intended since
it can occucr inside a field of the request.
=> Use of \n to split lines in batch transform.

src/gluonts/mx/distribution/lds.py, test/model/deepstate/test_deepstate_smoke.py
*Issue #, if available:* Fixes #908 
*Description of changes:* `mx.nd.split` has a weird behavior for `num_outputs==1`, in which case one axis always disappears even if `squeeze_axis=False` (and two disappear if `squeeze_axis=True`). This puts a safety net around these operations.
~~Will check with MXNet whether this is intended behavior or a bug.~~
*Edit:* this seems on purpose.
=> Fix LDS distribution for the case where sequence_length==1

src/gluonts/model/seq2seq/_forking_estimator.py, src/gluonts/model/seq2seq/_mq_dnn_estimator.py, test/model/seq2seq/test_model.py
- Fixes cardinality when `use_feat_static_cat = False` but `feat_static_cat` present in the dataset
- In this case cardinality was computed in `derive_auto_fields()` 
- Resulted in `AssertionError: You should setcardinality if and only if use_feat_static_cat=True`
- Added `test_feat_static_cat_smoke_test()` to toggle `use_feat_static_cat` on and off for datasets with `feat_static_cat` fields present or not
- Updated defaults:
`add_time_feature = True`
`enable_decoder_dynamic_feature = True`
=> Fixing cardinality array when use_feat_static_cat = False

src/gluonts/evaluation/_base.py
=> Defaulting MSIS to NaN when it can't be calculated.

src/gluonts/evaluation/backtest.py, test/dataset/test_multiprocessing_loader.py, test/model/conftest.py, test/model/deepvar/test_deepvar.py, test/model/gpvar/test_gpvar.py, test/model/naive_predictors/test_predictors.py, test/model/test_backtest.py, test/model/test_predictor.py, test/paper_examples/test_axiv_paper_examples.py
*Description of changes:* The `backtest_metrics` utility function is currently trying to do too much stuff: it can take optional training data, and both a predictor or an estimator, and behave differently based on what it's provided with. As a result, `backtest_metrics` needs to take all sorts of parameters as input (for example regarding multi-processing options in case training is run), and depends on a bunch of model definitions (like GluonEstimator and so on) and data loading utilities (like InferenceDataLoader).
I think this is bad design first of all, but in addition to it this makes it hard (if possible at all) to remove its dependency on MXNet: this prevents us from potentially making it nicely usable with other frameworks.
This PR is simplifying it by letting it take a …
=> Simplify backtest_metrics

src/gluonts/shell/__main__.py, src/gluonts/shell/sagemaker/__init__.py, src/gluonts/testutil/shell.py
Missing or incorrect mandatory Hyperparameters are leading to errors that are not captured inside the `failure` file inside the `output` folder. This PR fixes this problem by including the `env = TrainEnv(Path(data_path))` inside the `try` block and instantiate the `path` beforehand.
=> Shell: Fix writing of `output/failure` file in case of error in provided hyper-parameters.

src/gluonts/shell/train.py
#937
aggregate metrics and item metrics are now stored in the output folder where the model is stored.
=> Evaluation metrics now stored in output folder

src/gluonts/dataset/parallelized_loader.py
Fixes issue https://github.com/awslabs/gluon-ts/issues/837 
Removes legacy `__del__` method from `_MultiWorkerIter` that was used to prevent memory leaks.
*TODO*
=> Removing mp worker del method.

test/dataset/test_multiprocessing_loader.py
Mistakenly we were testing whether Inference and Validation data loaders were yielding the expected batch size, however, only the Training data loader really always has to yield `batch_size`d batches, since it's cyclic, whereas the other two data sets are not.
This PR corrects these logical errors and reflects this in the new test.
=> Fixed logical error in data_loder tests.

src/gluonts/model/trivial/mean.py, test/model/trivial/test_moving_average.py
- Added moving average.
-- This is a deterministic task (no distribution of observations is assumed)
-- For the case where _prediction_length_ = 1, the output is the standard moving average of the previous _context_length_ observations
-- For the case where _prediction_length_ > 1, the input target is appended with previous moving averages, further computing moving averages until _prediction_length_ of them are computed.
=> Implemented moving average

src/gluonts/model/simple_feedforward/_network.py, src/gluonts/mx/distribution/__init__.py, src/gluonts/mx/distribution/categorical.py, src/gluonts/mx/distribution/deterministic.py, src/gluonts/mx/distribution/gaussian.py, src/gluonts/mx/distribution/mixture.py, src/gluonts/mx/distribution/nan_mixture.py, test/distribution/test_mixture.py, test/distribution/test_nan_mixture.py
Added a distribution to model data which contains missing values.
=> NanMixture: Distribution to model missing values

src/gluonts/mx/distribution/deterministic.py, src/gluonts/mx/distribution/distribution_output.py, test/distribution/test_distribution_output_shapes.py
*Description of changes:* Fixes the `DeterministicOutput` class and add tests for it. This class is useful e.g. to implement inflated distributions (through a `MixtureDistributionOutput`).
cc @PascalIversen 
=> Fix DeterministicOutput, add tests

src/gluonts/dataset/common.py, src/gluonts/dataset/loader.py, src/gluonts/dataset/parallelized_loader.py
Fixing the FileDataset case with caching off for num_workers calculation to set it to the minimum dataset length across all the sub files
- Fixed bug with `num_workers > 1` on non-cached dataset with `3` time series so each file only has `1` time series
- We see timeout here because some workers will get assigned 0 time series series and the multiprocessing loader expects the worker to return batches and waits for the `timeout = 120` seconds max but the worker cannot produce batches with 0 time series and will be in a infinite loop
- Added len_per_file__() method to `FileDataset` class for the non-cached case to set `num_workers = min(num_workers, len(dataset_per_file)`
- Updated to take non-zero minimum using lambda function so if we have empty file it will default to the non-zero …
=> Fixing the FileDataset case with caching off for num_workers calculation

src/gluonts/model/seq2seq/_forking_estimator.py, test/model/seq2seq/test_model.py
- Fixed MQ-CNN with yearly freq and only time as the dynamic feature
- In this case no dynamic features are created because the time feature is empty for `Y` freq and `dynamic_feat` is `None`
- Updated to create the dummy zero feature in this case
- Added `test_mqcnn_covariate_smoke_test` to use `freq` = `Y` to test this.  Before would fail with `add_time_feature = True`, `add_age_feature = False` and `use_feat_dyanmic_real = True`
=>  Fixing case with only time features and yearly freq

src/gluonts/model/seq2seq/_forking_estimator.py, src/gluonts/model/seq2seq/_forking_network.py, src/gluonts/model/seq2seq/_mq_dnn_estimator.py, test/model/seq2seq/test_model.py
*Issue #, if available:* Replaces #936, adds the option of configuring seq2seq models with a distribution output instead of specific quantiles.
Joint work with @YuntianYeAWS 
=> Enable distribution output in seq2seq

src/gluonts/model/deepar/_network.py
I added an assertion to prevent the Mypy typing error:
`src/gluonts/model/deepar/_network.py:434: error: 'gluonts.mx.distribution.distribution.Distribution' object is not iterable`
=> Fixed DeepAR typing error

src/gluonts/model/seq2seq/_forking_network.py, src/gluonts/model/seq2seq/_mq_dnn_estimator.py, test/model/seq2seq/test_model.py
=> Fix docstrings, enable distr_output in MQRNN

src/gluonts/dataset/common.py, src/gluonts/model/seq2seq/_forking_estimator.py, src/gluonts/model/seq2seq/_forking_network.py, src/gluonts/model/seq2seq/_mq_dnn_estimator.py, src/gluonts/model/seq2seq/_transform.py, src/gluonts/transform/feature.py, test/model/seq2seq/test_forking_sequence_splitter.py, test/model/seq2seq/test_model.py, test/test_transform.py
*Issues:*
- Current forking copying of segments in the 3D forking decoder is slow
- This can dominate the computation for long prediction length and large number of RTS
- Time is spent in creating batches rather than training
- Can test less forking and interpolate from seq2seq and MQC(R)NN estimators
- Can use `num_forking` hp to interpolate from the `seq2seq` (`num_forking = 1`)  to full `MQ-C(R)NN` (`num_forking = context_length`)
- Added `num_forking` parameter to decide the amount of forking we want which defaults to `self.enc_len = context_length`
- Transpose operation moved to the beginning so we can take advantage of row-major caching and do one operation rather than within the loop
- Use `as_strides()` for the contiguous memory views instead of copies
- …
=> Adding support for `num_forking` as MQ-CNN hp

src/gluonts/shell/serve/app.py
New format:
```
[2020-09-29 09:54:26] [INFO] gluonts.serve Worker pid=64229: scored 56 using on avg 1.1 s/ts over the last 60 seconds.
[2020-09-29 09:54:30] [INFO] gluonts.serve Worker pid=64227: scored 41 using on avg 0.8 s/ts over the last 97 seconds.
```
=> Improved logging for batch-transform.

src/gluonts/mx/distribution/gamma.py, src/gluonts/mx/distribution/genpareto.py, test/distribution/test_mixture.py
*Issue* #1056
*Description of changes:* Description of changes: Gamma's log_prob(x) now returns -inf for x<=0 instead of NaNs, similarly with genpareto's log_prob(x) for x<0. Wherever there are NaN in either of the F.where() conditional vectors, then F.where() returns NaN at that entry as well, due to its indicator function multiplication: 1f(x) + np.nan0 = nan, since np.nan*0 return nan.
Therefore replacing log_prob(x) with log_prob(abs(x)) mitigates NaN returns and NaN gradients in cases of x<=0, without altering the value in cases of x>0. This is a known issue in pytorch as well pytorch/pytorch#12986.
Two corresponding pytests are also added.
=> Fix gamma nans

src/gluonts/mx/batchify.py, src/gluonts/support/util.py, src/gluonts/testutil/dummy_datasets.py, test/dataset/test_variable_length.py, test/support/test_util.py
- Moved `pad_arrays` to `util.py`
- Used `pad_to_size` function to remove duplicate code and return before calling `nd.pad` if no padding is needed.
- Moved `get_dataset` to `testutil/dummy_datasets`
- Moved `test_pad_arrays_axis` to `test/util.py`
=> Using pad_to_size function to remove duplicate code in pad_arrays

src/gluonts/model/seq2seq/_forking_estimator.py, src/gluonts/model/seq2seq/_forking_network.py, src/gluonts/model/seq2seq/_mq_dnn_estimator.py, test/model/seq2seq/test_model.py
https://github.com/awslabs/gluon-ts/issues/1069
- Updated default `scaling` for large to `True` to be used with `DistrOutput`
- Left default for `scaling_decoder_dynamic_feature` to be `False`
- Pass `scaling_decoder_dynamic_feature` to training and prediction networks
- Fix the shape of `loc` and `scale`
=> Fix scaling for MQ-(C|R)NN when distribution outputs are used

src/gluonts/mx/distribution/__init__.py, src/gluonts/mx/distribution/distribution_output.py, src/gluonts/mx/distribution/piecewise_linear.py, test/distribution/test_mixture.py, test/distribution/test_piecewise_linear.py
*Description of changes:* This adds the extension to the `PiecewiseLinearOutput` class which uses a fixed set of interpolation knots. Mainly authored by @canerturkmen 
=> Add piecewise linear quantile function output with fixed knots

src/gluonts/mx/distribution/mixture.py
related to #1066
The `value_in_support` property of the `MixtureDistributionOutput` was previously defaulting to zero. Fixing this to allow for mixtures which do not cover zero.
=> fix value_in_support of the MixtureDistributionOutput

src/gluonts/mx/distribution/gamma.py, test/distribution/test_mixture.py
fix for #1066
Added masking to prevent NaN gradients of the `Gamma` for `x=0`.
This is important for fitting mixture distributions such as: 
```python
mdo = MixtureDistributionOutput([GaussianOutput(), GammaOutput()]).
```
Example code:
```python
import mxnet as mx
from gluonts.mx.distribution import Gamma
a =mx.nd.array([1])
b =mx.nd.array([1])
a.attach_grad()
b.attach_grad()
with mx.autograd.record():
loss = mx.nd.mean(Gamma(a,b).loss(x=mx.nd.array([0])))
loss.backward()
print(a.grad)
print(b.grad)
```
will return
```python
[0.]
<NDArray 1 @cpu(0)>
[0.]
<NDArray 1 @cpu(0)>
```
instead of
```python
[nan]
<NDArray 1 @cpu(0)>
[0.]
<NDArray 1 @cpu(0)>
```
By submitting this pull request, I confirm that you can use, modify, copy, and …
=> fix Gamma distribution's NaN gradients for zero inputs

src/gluonts/dataset/loader.py, src/gluonts/dataset/util.py
*Issue #, if available:* This aims at fixing #1054
*Description of changes:* Apparently, to solve #1054 one needs to explicitly set the process start method to "spawn" on Linux platforms. However, the current way the multiprocess batching logic works does not allow that, because a generator is being passed to the spawned processes, which isn't allowed.
This PR fixes it so that all details (dataset, transformation, other options) are passed on to the processes, and each one of them constructs the generator on its own. So now the following works on a Linux platform with GPU:
```python
import multiprocessing
multiprocessing.set_start_method("spawn", force=True)
import mxnet as mx
from gluonts.dataset.repository.datasets import get_dataset
from gluonts.model.simple_feedforward import …
```
=> Refactor multiprocessing batcher to work with spawn method

src/gluonts/core/serde.py, src/gluonts/core/ty.py, test/core/test_serde.py, test/core/test_ty.py
=> Added ty.checked decorator.

src/gluonts/mx/trainer/_base.py
Before this change, the parameters of the model where updated even when the loss was NaN. The check for the NaN value was only at the end of the epoch and resulted in a warning. An error was thrown only if a NaN loss value was found in the first epoch with a suggestion of reducing the initial learning rate, otherwise the training would continue resulting in undesired behaviour, like training getting stuck and freezing the CPU, which I experienced firsthand.
I changed the code to throw a warning and ignore NaNs during training. With this change, the training does not get stuck anymore, although the previously thrown error now triggers only when ALL the batches of the first epoch give NaNs.
I think there should probably be a parameter to select the appropriate behaviour when encountering …
=> Ignore NaN values during training and throw a warning (training got stuck before)

README.md, REFERENCES.md
=> add more references

test/model/tft/test_model.py
*Description of changes:* This test was disable because it would time out frequently; reducing the number of batches used to make it faster.
=> Speed up and re-enable TFT test

src/gluonts/dataset/loader.py, src/gluonts/dataset/util.py, src/gluonts/itertools.py, src/gluonts/shell/sagemaker/params.py, test/test_itertools.py
* Move iterator utilities to a dedicated itertools module
* Remove `shuffle` (not used) introduce `pseudo_shuffle` instead (this is based on the mechanism we're using in the data loader, which is just as general)
* Add the `cache` util that caches an iterable so that the second pass through it is faster. This can be used to cache datasets or transformed datasets (as long as their iteration is deterministic, i.e. no instance splitting or other random transformations).
=> Move itertools to dedicated module, add caching utility

src/gluonts/transform/feature.py, test/test_transform.py
The missing value imputations methods break if the window is all `nan` values. 
=> Masking edge case fix

src/gluonts/model/rotbaum/_predictor.py, src/gluonts/model/tpp/predictor.py, src/gluonts/mx/model/predictor.py
*Issue #, if available:*  #1133
Added argument `dataset` to all `as_symbol_block_predictor` functions.
Did not want to remove `batch` argument to allow for backward compatibility.
=> added dataset as argument to as_symbol_block_predictor

src/gluonts/model/rotbaum/_estimator.py, src/gluonts/model/rotbaum/_predictor.py
*Description of changes:* Since Rotbaum is not based on Gluon, there's no need to inherit from GluonEstimator and GluonPredictor.
Also removed the `__call__` method from `TreePredictor`, in favor of the more explicit `train`.
@zoolhasson I'm trying to add you as a reviewer
=> Fix rotbaum

src/gluonts/evaluation/_base.py, src/gluonts/model/tft/_estimator.py, src/gluonts/model/tpp/predictor.py, src/gluonts/mx/distribution/__init__.py, src/gluonts/mx/distribution/neg_binomial.py, src/gluonts/mx/distribution/poisson.py, src/gluonts/mx/model/predictor.py, src/gluonts/mx/trainer/_base.py, test/distribution/test_distribution_sampling.py, test/distribution/test_mx_distribution_inference.py
- added two rerun markers to tests as a quick fix, because the maximum likelihood inference of the inflated  discrete distributions is currently unstable. 
- all other changes got introduced by black, I have the right black version (19.10b0), so I don't get whats going on there...
=> fix inflated discrete distribution tests

docs/examples/synthetic_data_generation_tutorial/tutorial.md, src/gluonts/dataset/artificial/_base.py, src/gluonts/dataset/artificial/recipe.py, test/dataset/artificial/test_recipe.py
Introduce a functional api for data generation recipes. I.e. you can write
```python
stddev = rcp.RandomUniform(low=0, high=1, shape=(1,))
x = rcp.RandomGaussian(stddev=stddev)
evaluate(dict(x=x), length=...)
```
Also add support for multiple return values (currently only used in in a test).
```python
a, b = SomeOperator(...)
evaluate(dict(
a=a
))
```
This change is fully backwards compatible for now...
=> introduce functional api for data generation recipes

src/gluonts/itertools.py, test/test_itertools.py
*Issue #, if available:* fixes #1157 
*Description of changes:* `cyclic` would result in an infinite loop when given an empty iterable, causing worker processes to hang when `num_workers > len(dataset)`. This fixes it and adds a test.
=> Fix edge case for `cyclic`

src/gluonts/dataset/loader.py, src/gluonts/evaluation/_base.py
*Description of changes:* this aligns the convention between data loader and evaluator with respect to the `num_workers` parameter: `0` or `None` means "no workers" (i.e. only main process is processing), while values larger than `0` cause subprocesses to be spawned.
Minor related fixes/simplifications are included.
=> Align `num_workers` convention between loader and evaluator

src/gluonts/dataset/artificial/recipe.py, test/dataset/artificial/test_recipe.py
- includes a `lift` decorator to lift a function for data generation
- auto generated lifted numpy interface
- support `Length` operator to determine the length from the data
=> include lift decorator and lifted numpy for data generation recipes

src/gluonts/model/naive_2/_predictor.py, src/gluonts/model/npts/_model.py, src/gluonts/model/npts/_predictor.py
#1170
added item_id argument to NPTSPredictor.predict_time_seriesand NPTS.predict, 
=> Added item_id to NPTS and Naive2 forecasts

src/gluonts/transform/feature.py, test/test_dataset_mutability.py
Some transformation can potentially change the original dataset which affects the upcoming transformations and batches that are created. This depends on the fields that each transformation uses and the type of the dataset.
This PR includes a general fix for the `AddObservedValueIndicator` transformation that in some cases changes the `target` field of the original dataset. Also, some tests are included with some other transformations to ensure proper behaviour. 
=> fixes in dataset mutability

src/gluonts/mx/distribution/__init__.py, src/gluonts/mx/distribution/binned.py, src/gluonts/mx/distribution/deterministic.py, src/gluonts/mx/distribution/distribution.py, src/gluonts/mx/distribution/genpareto.py, src/gluonts/mx/distribution/mixture.py, src/gluonts/mx/distribution/transformed_distribution.py, test/distribution/test_default_quantile_method.py, test/distribution/test_mx_distribution_inference.py
- Added quantile function based on cdf bisection.
- Added a test that ensures we get the correct quantiles.
This method is used as the default in the `Distribution` class unless it is overwritten by the corresponding subclasses. It requires a cdf method. 
=> Added quantile function based on cdf bisection

src/gluonts/model/estimator.py, src/gluonts/model/wavenet/_estimator.py, src/gluonts/mx/trainer/_base.py
*Description of changes:* This makes the `Trainer` interface easier to use e.g. for interactive usage.
Note: while this is a breaking change
1. existing estimators in the package are unaffected
2. any custom estimator that simply inherit from `GluonEstimator` (and do not customize how the `Trainer` is used) will also continue to work as before
3. previously trained and serialized predictors will continue to work (no change in how predictors work)
=> Remove input_names argument to trainer __call__

src/gluonts/model/deepar/_estimator.py, src/gluonts/model/gpvar/_estimator.py, src/gluonts/model/lstnet/_estimator.py, src/gluonts/model/n_beats/_estimator.py, src/gluonts/model/san/_estimator.py, src/gluonts/model/simple_feedforward/_estimator.py, src/gluonts/model/transformer/_estimator.py, src/gluonts/model/wavenet/_estimator.py
Make the `train_sampler` an argument for models. This allows us to configure the sampling strategy and to experiment with different strategies.
=> make train_sampler a parameter for most models

src/gluonts/dataset/loader.py, src/gluonts/model/wavenet/_estimator.py, src/gluonts/mx/model/estimator.py, src/gluonts/mx/trainer/_base.py, test/dataset/test_multiprocessing_loader.py, test/dataset/test_variable_length.py, test/distribution/test_distribution_output_shapes.py, test/model/deepar/test_deepar_auxiliary_outputs.py
*Description of changes:* Before this, the `num_batches_per_epoch` is not really used in `Trainer`, but only stored for estimators to read (to configure the data loader). This is a bit confusing if one uses the `Trainer` class directly: `num_batches_per_epoch` can be set, but will not have any effect (only the one passed into the `TrainDataLoader` matters).
This PR proposes to make this clearer, as follows:
* Remove the `num_batches_per_epoch` argument to `TrainDataLoader`, which effectively becomes an endless iterator
* Enforce the epoch duration directly in the `Trainer`, by `islice`-ing `num_batches_per_epoch` batches from the data loader
=> Fix num_batches_per_epoch in Trainer

docs/examples/basic_forecasting_tutorial/tutorial.md, docs/examples/extended_forecasting_tutorial/extended_tutorial.md, src/gluonts/dataset/loader.py, src/gluonts/itertools.py, src/gluonts/model/canonical/_estimator.py, src/gluonts/model/deep_factor/_estimator.py, src/gluonts/model/deepar/_estimator.py, src/gluonts/model/deepstate/_estimator.py, src/gluonts/model/deepvar/_estimator.py, src/gluonts/model/gp_forecaster/_estimator.py, src/gluonts/model/gpvar/_estimator.py, src/gluonts/model/lstnet/_estimator.py, src/gluonts/model/n_beats/_estimator.py, src/gluonts/model/san/_estimator.py, src/gluonts/model/seq2seq/_forking_estimator.py, src/gluonts/model/seq2seq/_seq2seq_estimator.py, src/gluonts/model/simple_feedforward/_estimator.py, src/gluonts/model/tft/_estimator.py, src/gluonts/model/tpp/deeptpp/_estimator.py, src/gluonts/model/tpp/predictor.py, src/gluonts/model/transformer/_estimator.py, src/gluonts/model/wavenet/_estimator.py, src/gluonts/mx/model/estimator.py, src/gluonts/mx/trainer/_base.py, test/paper_examples/test_axiv_paper_examples.py, test/test_itertools.py
1. Simplify data loader into a single iterable `DataLoader` type, that does one thing. Legacy `TrainDataLoader`, `ValidationDataLoader`, `InferenceDataLoader` are kept as "alternative constructors" for backward compatibility, they just decorate `DataLoader`'s input/output sequence with very general purpose itertools, in order to get the desired behaviour.
2. Turn some itertools from generators into proper iterable types, so as to make them pickleable, which is needed for multiprocessing.
3. Re-introduce a (optional) `num_batches_per_epoch` argument to the `TrainDataLoader` (removed in #1202) to enable making the data loader of finite length. This allows using this otherwise-infinite-length iterator with other training loops (e.g. PyTorch Lightning) that don't do …
=> Simplify data loader, deprecate Trainer's batch_size

src/gluonts/mx/block/sndense.py, src/gluonts/mx/block/snmlp.py, src/gluonts/mx/distribution/bijection.py, src/gluonts/mx/distribution/iresnet.py
Normalizing flow is derived from `mx.gluon.Block` which makes it hard to use it in existing gluonts networks that are derived from `mx.gluon.HybridBlock`. 
=> Make Normalizing Flow a HybridBlock instead of a Block

src/gluonts/model/deepstate/issm.py, src/gluonts/mx/distribution/inflated_beta.py, test/distribution/test_inflated_beta.py
*Issue #, if available:* addresses [#1211](https://github.com/awslabs/gluon-ts/issues/1211)
*Description of changes:* The various inflated beta distribution classes used `F.logical_or` to mask ones and zeros (for which the loss function is undefined), but there is no `logical_or` method for `mxnet.symbol`.
We now use `F.broadcast_logical_or` which exists as a method of both `mxnet.ndarray` and `mxnet.symbol`, either of which can be imported as `F`.
=> Use broadcast_logical_or in inflated_beta

src/gluonts/torch/model/predictor.py
currently this does not work when the tensors are on the gpu
=> Fixed pytorch's predict to numpy helper

src/gluonts/mx/block/quantile_output.py, src/gluonts/mx/distribution/lds.py, test/model/seq2seq/test_quantile_loss.py
Quantile loss class has an argument 'quantile_weights' which is set to be 'None' as a default. This argument is going to be used when computing approximate CRPS loss.
1. I found the bug when this argument is passed. The type must be 'List', but it is operated under nd.array.asscalar(), giving error as follows 
`E           AttributeError: 'float' object has no attribute 'asscalar'`
`Python-gluonts/src/gluonts/mx/block/quantile_output.py:101: AttributeError`
2.  Fixed the type/AttributeError and added a proper pytest example under 'test_quantile_loss.py' file. 
=> Fix type error for using quantile_weights and add a proper Pytest 

requirements/requirements.txt, src/gluonts/model/deepstate/issm.py, src/gluonts/time_feature/__init__.py, src/gluonts/time_feature/_base.py, test/time_feature/test_features.py
*Description of changes:* This PR adds a test for the expected ranges of time features, and fixes the features so that they fall within them. At the same time it splits the `normalized=False` case in separate classes.
A pandas deprecation (`DatetimeIndex.weekofyear`) has been updated as per the docs (https://pandas.pydata.org/docs/reference/api/pandas.DatetimeIndex.weekofyear.html#pandas.DatetimeIndex.weekofyear) and the requirement has been bumped accordingly.
*Background:* Some time features are out of the `[-0.5, 0.5]` range (or `[0, cardinality)` when not normalized) because some of them are 1-based in pandas. Some of them were also slightly off because of edge cases (e.g. leap years).
This is a problem mainly for state space models that use unnormalized features to construct ISSM …
=> Fix time features ranges, split unnormalized features

src/gluonts/model/deepstate/_estimator.py, src/gluonts/model/deepstate/issm.py, test/model/deepstate/test_issm.py
*Issue #, if available:* addresses #1200 
*Description of changes:* Using custom ISSMs in DeepState (i.e. other than the default one for the given frequency), does not work because the time features from which coefficients are constructed always fall back to the default ones. This PR changes this, by coupling each ISSM with the time feature that is needed to derive its coefficients.
Tests are added for the ISSM classes, which were not there before.
=> Improve ISSM interface

src/gluonts/model/n_beats/_estimator.py, src/gluonts/model/n_beats/_network.py
*Issue:*
NBEATS implementation differs from [the one of the authors](https://github.com/ElementAI/N-BEATS/blob/master/models/nbeats.py). In particular it lacks proper [masking of the input](https://github.com/ElementAI/N-BEATS/blob/master/models/nbeats.py#L72), which is also described in the [paper](https://arxiv.org/pdf/1905.10437.pdf) at the end of page 26.
Added proper input masking and optional (default to False) input scaling. Input scaling is used in the [meta-learning version of NBEATS](https://arxiv.org/pdf/2002.02887.pdf) to account for time series of different magnitudes. Here, scaling is implemented similarly to DeeAR (using MeanScaler) while in the paper the input/output of the model is scaled/descaled by the maximum value in the input.
Strangely, the …
=> Input masking and scaling in NBEATS (following authors' implementation)

src/gluonts/transform/split.py
Else it ends up being `float64` and needs to be cast down when checking with `past_observed_values` etc.
=> set is_pad_field's type to the data type in spilters

src/gluonts/torch/modules/distribution_output.py
My mistake... `AffineTransform` doesn't take `None` for `loc` or `scale`.
=> Pytorch's AffineTransform doesn't take None as inputs

src/gluonts/torch/model/predictor.py
This allows the Pytorch model to be used on sagemaker after training on a GPU for example. Again apologies for these tiny PRs. cc @edrinb-zalando 
=> Allow Pytorch predictor to be loaded on different devices

src/gluonts/model/forecast.py, src/gluonts/mx/model/forecast.py
…tion forecast to quantile forecast
method that allows conversion from sample forecast to quantile forecast and distribution forecast to quantile forecast might be helpful in developing AutoGluon for GluonTS as quantile forecasts are easier to be shown as a data frame.
Add two methods: 
SampleForecast.to_quantile_forecast
DistributionForecast.to_quantile_forecast
=> Add to_quantile_forecast method to Forecast classes

.github/ISSUE_TEMPLATE/config.yml
*Description of changes:* This puts a link to the Discussion section in the Issue submission form, so that (hopefully) questions and discussions are directed there
=> Add discussions link to issue templates form

src/gluonts/model/n_beats/_network.py
Since to compute `seasonal_error` we are taking the mean, `factor` is not needed. See also the [N-BEATS authors implementation](https://github.com/ElementAI/N-BEATS/blob/04f56c4ca4c144071b94089f7195b1dd606072b0/common/torch/losses.py#L61).
=> Fixed MASE in N-BEATS: removed redundant factor

requirements/requirements.txt
*Description of changes:* the recent release of numpy 1.20 broke some of our serde logic. This limits compatibility to <1.20, while we figure out how to fix it.
=> Restrict numpy to <1.20

.github/workflows/docs.yml
This allows pushing the built website to S3 using the docs workflow: there, docs are built on `push` and `pull_request` events, but the content is pushed to S3 only on `push` (since forks that issue pull requests don't have the required secrets to access S3).
Website pushed from the base branch of this PR: http://gluon-ts.s3-accelerate.dualstack.amazonaws.com/deploy-docs-via-gh-workflows/tutorials/index.html
=> Deploy website from docs workflow

src/gluonts/dataset/common.py
*Issue #, if available:* No issue created
*Description of changes:* I found a very small spelling error in the `ListDataset`documentation and fixed it.
=> Fix spelling error in ListDataset docstring

src/gluonts/torch/model/predictor.py
I cannot set the lead_time to PyTorchPredictor constructor for my LSTNet model.
=> Added lead_time argument to PyTorchPredictor

REFERENCES.md
- Adding paper reference for the Lotka-Volterra AutoODE code: https://github.com/awslabs/gluon-ts/tree/master/src/gluonts/nursery/auto_ode
- Fixing minor typos in references
=> Adding references for the AutoODE method

docs/tutorials/forecasting/extended_tutorial.md, docs/tutorials/forecasting/howto_pytorch_lightning.md, docs/tutorials/forecasting/quick_start_tutorial.md, evaluations/generate_evaluations.py, examples/benchmark_m4.py, examples/evaluate_model.py, examples/persist_model.py, examples/run_rolling_forecast_backtest.py, examples/warm_start.py, src/gluonts/evaluation/__init__.py, src/gluonts/evaluation/backtest.py, test/dataset/test_multiprocessing_loader.py, test/model/conftest.py, test/model/deepvar/test_deepvar.py, test/model/gpvar/test_gpvar.py, test/model/lstnet/test_lstnet.py, test/model/naive_predictors/test_predictors.py, test/model/test_backtest.py, test/model/test_predictor.py, test/paper_examples/test_axiv_paper_examples.py, test/torch/model/test_simple_torch_model.py
* Set a default `num_samples` in `make_evaluation_predictions`, which is annoying to set every time even when it is not needed.
* Fix docstrings
* Shorten import paths across the `gluonts.evaluation` package (backward compatible, old paths still available, but references to them are removed here)
=> Set default num_samples, shorten some import paths

src/gluonts/model/deepvar/_estimator.py
Now we normalize the freq str so it works for e.g. different `W-...` str
=> Fix deepVAR time feature freq str

src/gluonts/model/tft/_transform.py
`pad_block` is always float causing long tensors to be cast to floats as well.
set the `pad_block`'s type to the `d[field].dtype`
=> TFT transform fix casting to floats

src/gluonts/model/rotbaum/_lgb_wrapper.py, src/gluonts/model/rotbaum/_model.py, src/gluonts/model/rotbaum/_predictor.py
*Description of changes:* Added lightgbm support for QRX/Rotbaum. Instantiate a an lgb_wrapper object, and then feed into the model parameter in QRX/Rotbaum.
=> Added lightgbm support for QRX/Rotbaum

examples/dockerfiles/Dockerfile.gpu, examples/dockerfiles/Dockerfile.r, src/gluonts/shell/train.py, src/gluonts/testutil/shell.py
Some of the [dockerfiles](examples/dockerfiles) cannot be built/does not execute properly, this PR fixes this. 
These are the problems which this PR addresses:
1. The GPU image crashes on SageMaker due to MXNET_USE_FUSION being enabled. 
2. The GPU image crashes when passing `num_workers` as a hyperparameter. 
3. The mxnet version in the requirements file is unavailable when building the [R image](examples/dockerfiles/Dockerfile.R) so the R image fails to build.
*Problem 1* 
This occurs when the gpu image is run. 
For example running the SimpleFeedForwardEstimator on the electricity dataset with these hyperparameters:
```
epochs	1
forecaster_name	gluonts.model.simple_feedforward.SimpleFeedForwardEstimator
freq	D
prediction_length	7
```
Results in this error …
=> Fix dockerfiles

requirements/requirements-extras-sagemaker-sdk.txt
[Tests](https://github.com/awslabs/gluon-ts/pull/1261/checks?check_run_id=2277104757) fail for Python3.6, because there is an ImportError inside fsspec since the latest update to 0.9.0 (see https://github.com/intake/filesystem_spec/issues/597 or https://github.com/dask/s3fs/issues/457).
```
___ ERROR collecting test/nursery/sagemaker_sdk/test_entry_point_scripts.py ____
ImportError while importing test module '/home/runner/work/gluon-ts/gluon-ts/test/nursery/sagemaker_sdk/test_entry_point_scripts.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test/nursery/sagemaker_sdk/test_entry_point_scripts.py:23: in <module>
from gluonts.nursery.sagemaker_sdk.defaults import NUM_SAMPLES, QUANTILES …
```
=> Fix s3fs ImportError for fsspec 0.9.0

test/dataset/test_multiprocessing_loader.py
One of the flaky tests for the multiprocessing loader fails constantly, skipping the test for now as it often fails for unrelated commits.
=> Skip flaky test of multiprocessing loader.

src/gluonts/model/tft/_layers.py
score attention mask should be -inf, so that after softmax, score in masked will be zero.
Mask with 1e-9 make no sense, it should be -1e9
=> fix bug about attention mask

test/evaluation/test_evaluator.py, test/evaluation/test_metrics.py
This PR adds unit tests to the metrics used when backtesting.
Worklog:
=> Add unit tests for metrics.

src/gluonts/model/rotbaum/_model.py
*Description of changes:* Made QRX faster by not computing quantiles for all bins ahead of time, but rather in an ad hoc fashion and caching the results.
=> made QRX faster by not computing quantiles for all bins

src/gluonts/evaluation/_base.py
This pr adds logic which allows users to choose how per-timeseries metrics should be aggregated when calling `Evaluator.get_aggregate_metrics`.
=> Add strategies for aggregating metrics to Evaluator class.

src/gluonts/transform/convert.py, src/gluonts/transform/feature.py, test/test_transform.py
Related to creating dedicated neural intermittent demand models in GluonTS.
This PR adds two simple transformation objects that are meant to specifically deal with intermittent time series. Namely, `AddTrailingZeros` simply adds the number of zero valued time steps that are trailing in each of the target time series, allowing models to explicitly condition on the number of steps since the last 'demand' point when making a prediction. `SparseToDense` transformation takes a univariate time series and converts it to a size-interval format as often used in intermittent demand forecasting (e.g., in Croston's method).
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms …
=> Add transform objects for dealing with sparse time series.

test/activation/test_activations.py
*Issue #, if available:* #1374
Tests against mxnet 1.8 cannot be enabled because the pypi package for windows is not available. However this PR passes tests on macos and linux when using mxnet 1.8.
=> Fixes for MXNet 1.8

src/gluonts/time_feature/_base.py
```
def __call__(self, index: pd.DatetimeIndex) -> np.ndarray:
>       return (index.isocalendar().week - 1).map(float)
E       AttributeError: 'DatetimeIndex' object has no attribute 'isocalendar'
```
According to https://github.com/awslabs/gluon-ts/issues/1335 we support pandas >= 1.0, but when using pandas < 1.1 we get the displayed error for `class WeekOfYearIndex` and `class WeekOfYear`.
Added try block around `isocalendar()` function call and replaced it for the given error with the respective implementation.
=> fix compatibility for pandas < 1.1 in `time_feature/_base.py`

src/gluonts/mx/batchify.py, test/dataset/test_variable_length.py
batchify functions for handling variable length arrays handled mxnet arrays, which were marked as todos. this PR removes this, restricting the accepted array types to numpy arrays. moreover, it exposes the `is_right_pad` option, already available in `pad_to_size`, also in `batchify` and `stack`. This allows users to specify whether the arrays should be padded on the right (as is the mxnet convention, in functions like `SequenceMask`) or left.
=> adjustments to variable length functionality in batchify

requirements/requirements-docs.txt
*Description of changes:* The latest mxtheme==0.3.16 gave issues in docs builds: https://github.com/awslabs/gluon-ts/pull/1450/checks?check_run_id=2543302170
We will unlock or bump this version at some other stage.
=> Lock the version for mxtheme to 0.3.15

src/gluonts/mx/model/estimator.py
=> Fix missing import in `gluonts.mx.model.GluonEstimator`

src/gluonts/time_feature/seasonality.py, test/time_feature/test_seasonality.py
`get_seasonality` does not support min freq at the moment.
Added a default seasonality for min, namely `60*24`
=> support Min freq for get_seasonality() method

src/gluonts/model/renewal/__init__.py, src/gluonts/model/renewal/_estimator.py, src/gluonts/model/renewal/_network.py, src/gluonts/model/renewal/_predictor.py, src/gluonts/model/renewal/_transform.py, src/gluonts/transform/feature.py, test/model/renewal/__init__.py, test/model/renewal/test_model.py, test/model/renewal/test_predictor.py
This PR implements deep renewal processes for intermittent demand forecasting, introduced [here](https://arxiv.org/pdf/2010.01550.pdf).
In short, deep renewal processes are neural probabilistic forecasting models that operate on the bivariate interval-size process (i.e., the time between each positive demand point, and the sizes of positive demand) as is common in the intermittent demand literature, instead of directly operating on the sparse univariate demand process. This allows the process to naturally represent patterns such as quasi-periodicity.
This PR adds the estimator and network components, as well as custom (i) transform, (ii) output transform, and (iii) predictor objects that are able to handle variable-length arrays. It also …
=> Deep renewal processes for intermittent demand forecasting

src/gluonts/model/rotbaum/_model.py
Fixed a tiny but significant bug, whereby pandas series had ".values()" but should have had ".values".
=> Fixed bug: ".values()" to ".values"

src/gluonts/model/r_forecast/R/forecast_methods.R, src/gluonts/model/r_forecast/__init__.py, src/gluonts/model/r_forecast/_predictor.py, test/model/r_forecast/test_r_predictor.py
*Issue #, if available:  [255](https://github.com/awslabs/gluon-ts/issues/255)*
Several fixes:
* For `thetaf`, instead of repeating mean forecasts, the fix now returns quantile forecasts correctly by first obtaining prediction intervals
* `simulate` is not defined on tbats model; returns quantile forecasts by first obtaining prediction intervals
* Fixes the non-functional `Croston` and `MLP` methods; need to pass prediction length to obtain forecasts directly.
* On the python-side, allows obtaining quantile forecasts from R instead of samples-based forecast.
This worked on the following versions:
* R version 3.6.3 (2020-02-29) and `forecast` version 8.15
* R version 4.1.0 (2021-05-18) and `forecast` version 8.14
By submitting this pull request, I confirm that you …
=> R fixes for methods that produce point forecasts or prediction intervals directly

src/gluonts/dataset/repository/_lstnet.py
The following snippet
```python
from gluonts.dataset.repository.datasets import get_dataset
solar = get_dataset("solar-energy", regenerate=True)
next(iter(solar.train))["start"].freq
```
prints out `<10 * Minutes>` but the data is actually aggregated hourly via `sum` via [this](https://github.com/awslabs/gluon-ts/blob/1e9e8f07aa6921f6f8eba4f366a71a6fcf933916/src/gluonts/dataset/repository/_lstnet.py#L115) and [that](https://github.com/awslabs/gluon-ts/blob/1e9e8f07aa6921f6f8eba4f366a71a6fcf933916/src/gluonts/dataset/repository/_lstnet.py#L42-L43).
The issue is caused by the wrong frequency being stored in the metadata whenever some aggregation frequency is specified. This appears to be the case only for `solar-energy`. After the fix, the above snippet correctly …
=> Fix frequency in metadata for lstnet datasets

src/gluonts/model/seasonal_naive/_estimator.py
Addition of dummy estimator for Seasonal Naive. This allows to use seasonal naive from the shell.
=> add dummy estimator for seasonal_naive

src/gluonts/model/trivial/_estimator.py
Addition of dummy estimator for trivial models, i.e. constant, identity, mean and moving average. 
This allows to use these from the shell.
=> add dummy estimator to trivial models

test/distribution/test_flows.py
=> loosen RTOL in `test/distribution/test_flows.py` to make `test_flow_invertibility` pass

src/gluonts/dataset/repository/_artificial.py, src/gluonts/dataset/repository/_gp_copula_2019.py, src/gluonts/dataset/repository/_lstnet.py, src/gluonts/dataset/repository/_m3.py, src/gluonts/dataset/repository/_tsf_datasets.py, src/gluonts/dataset/repository/_tsf_reader.py, src/gluonts/dataset/repository/datasets.py
This PR adds 11 more datasets from the [Monash Time Series Forecasting Repository](https://forecastingdata.org/). It uses a default prediction length whenever none is available, depending on the frequency of the data. Additionally, this PR includes the following changes:
- Users are able to specify a custom `prediction_length` in the `get_dataset` function. This will override any defaults and takes effect whenever `regenerate=True` or the dataset is generated for the first time.
- The PR fixes a bug in the frequency calculation for the Monash datasets where (1) a minutely frequency was parsed as monthly and (2) `half_<frequency>` couldn't be parsed.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, …
=> Add additional datasets from the Monash Time Series Forecasting Repository

src/gluonts/model/rotbaum/_model.py
*Description of changes:* Made it so QRX can be imported using the name LSF. LSF stands for "Level Set Forecasting", and emphasizes that QRX can be used with any point forecasting algorithm, not just XGBoost.
=> Add "LSF" as an alternative name to "QRX"

src/gluonts/model/seq2seq/_mq_dnn_estimator.py
*Issue #1644*
[MQCNNEstimator](https://github.com/awslabs/gluon-ts/blob/eb89e4ee2dd7308842381b6c425197bb3ae6eed6/src/gluonts/model/seq2seq/_mq_dnn_estimator.py#L34) and [MQRNNEstimator](https://github.com/awslabs/gluon-ts/blob/eb89e4ee2dd7308842381b6c425197bb3ae6eed6/src/gluonts/model/seq2seq/_mq_dnn_estimator.py#L303) were missing the `batch_size` attribute (after this attribute was removed from `Trainer`).
This PR only add the `batch_size` attribute to the 2 classes and call their parent constructor [ForkingSeq2SeqEstimator](https://github.com/awslabs/gluon-ts/blob/eb89e4ee2dd7308842381b6c425197bb3ae6eed6/src/gluonts/model/seq2seq/_forking_estimator.py#L72) with the batch_size attribute.
By submitting this pull request, I confirm that you can use, modify, copy, …
=> Add batch_size attribute to MQCNNEstimator and MQRNNEstimator

src/gluonts/torch/modules/distribution_output.py, test/torch/modules/test_torch_distribution_inference.py
*Issue #, if available:* Fixes #1646
*Description of changes:* `NegativeBinomialOutput` was calling `torch.distributions.NegativeBinomial` with the wrong constructor argument (second positional argument). This PR makes sure the right argument `logits` is passed. Ideally, the `domain_map` from `DistributionOutput` should return a dictionary of kwargs for the distribution class; however, modifying that would require some broader changes, so this solution is simpler. We can decide to change the API of `DistributionOutput` at a later stage, if we thing that's necessary.
**Please tag this pr with at least one of these labels to make our release process …
=> Fix NegativeBinomial constructor args in NegativeBinomialOutput

src/gluonts/model/deepar/_estimator.py
This assert statement prevents using DeepAR estimator from shell with `use_feat_static_cat = False` when dataset contains static categorical features.
=> Allow disabling static features in DeepAR regardless of cardinality.

requirements/requirements-docs.txt, requirements/requirements-extras-anomaly-evaluation.txt
Some issue started occurring since `numba==0.54` was released (released August 20) and `ipykernel==6.2.0`:
```
ImportError: numpy.core.multiarray failed to import  # because of numba
[...]
TypeError: 'coroutine' object is not subscriptable  # because of ipykernel
```
This PR is capping it temporarily.
=> Cap numba<0.54, ipykernel<6.2.0

src/gluonts/torch/modules/distribution_output.py
scale neg bin parameters as it should return integers.
=> Fix scaling for pytorch negative binomial output

src/gluonts/model/deepvar_hierarchical/_estimator.py, src/gluonts/model/deepvar_hierarchical/_network.py
In the hierarchical forecaster, use `dot` instead of `linalg_gemm2` for matrix-vector multiplication since for the latter one needs to expand and broadcast dimensions of the projection matrix (unnecessarily resulting in memory issues).
=> Hierarchical: replace linalg_gemm2 by dot

.github/workflows/tests.yml, pytest.ini
Github Action uses workers with 2 CPUs by default. Thus, parallelising tests should make the runs considerably faster.
=> Use xdist (n=2) in tests.

src/gluonts/model/rotbaum/_preprocess.py
*Description of changes:* The way that the dynamic real and categorical features had been implemented in this code had incorrect logic: it leaked data from the future by taking the entirety of those features (raw, without any adjustments) across all timesteps in each context window. This fixes this problem.
Looking at the rest of the code, I highly suspect that there are still unresolved issues with one hot encoding and whether the notion of cardinality integrates well in this code, but I did not resolve those issues due to time constraints. In particular, the current implementation requires 'feat_static_cat' to be a key in the dataset (even if empty), is this desired behavior?
By submitting this pull request, I confirm that you can use, modify, copy, and …
=> Fixed data leakage bug in implementation of dynamic real and categorical features

src/gluonts/model/rotbaum/README_LSF.ipynb
*Description of changes:* added the missing word "not" in the LSF readme.
=> added missing word in readme

src/gluonts/dataset/repository/_util.py, test/dataset/repository/__init__.py, test/dataset/repository/test_util.py
Change to `cardinality` output in the metadata.
According to Gluonts template `feat_static_cat`-entry of metadata.json is a list of `CategoricalFeatureInfo` ``[(feature_name, cardinality),...]``:
https://github.com/awslabs/gluon-ts/blob/d7679a5f239cbfd9e885dfdfe5312eb292353f73/src/gluonts/dataset/common.py#L74-L86
Currently this list only contains one element with cardinalies of all features as a list. This PR changes the structure of `feat_static_cat`-entry to contain information on each categorical feature separately (see example below).
Example: For two cat-features the change would output the metadata
```json
{
"freq": "1M",
"prediction_length": 18,
"feat_static_cat": [
{
"name": "feat_static_cat_1",
"cardinality": "1428"
},
{
"name": "feat_static_cat_2",
"cardinality": "6"
}
]
}
``` …
=> changed metadata creation function

src/gluonts/model/seq2seq/_mq_dnn_estimator.py
=> Extend default quantiles for MQ* Estimators to match MSIS quantiles.

src/gluonts/torch/model/estimator.py
Allows the fit method to resume from a checkpointed file and allow validation dataloader to use multiple workers.
=> [pytorch] allow train to resume from checkpoint

src/gluonts/mx/distribution/neg_binomial.py
*Issue #, if available:* Fixes #1881
*Description of changes:* The `sample` method of `NegativeBinomial` contained some arbitrary parameter clipping that distorts the distribution in extreme cases. This PR removes it.
=> Fix negative binomial sampling

src/gluonts/mx/distribution/neg_binomial.py
*Issue #, if available:* May fix #833 and #1796
*Description of changes:* This replaces #1890, with a much simpler fix that appears to solve the NaN issue when training DeepAR with a `NegativeBinomialOutput`, at least in the [example](https://github.com/awslabs/gluon-ts/issues/1796#issuecomment-1041392110) I described in #1796.
The issue appears to be with our `softplus`, which may return very small negative values.
=> Fix negative binomial parameter map

src/gluonts/dataset/repository/_m5.py, src/gluonts/dataset/repository/datasets.py
*Issue #, if available:* n/a
*Description of changes:* Currently, the M5 dataset cannot be generated. On `materialize_dataset`, the `<default_dir>/m5` is deleted when `regenerate` is set to `True`, but it has to contain the `.csv` files obtained from Kaggle. When not setting `regenerate=True`, the dataset is never generated because the `.csv` files are located in `<default_dir>/m5`.
This PR adds another parameter to the dataset recipe such that the M5 data can be sourced from another directory (which makes more sense anyway, imo).
**Please tag this pr with at least one of these labels to make our release process faster:** BREAKING, new feature, bug …
=> Add file path argument to m5 dataset generation

.github/workflows/docs.yml
Merge this if #1901 gets closed. Updating ownership of the objects created in the bucket to prevent #1901 from happening.
=> Update docs.yml to set right ownership for pushed objects.

src/gluonts/mx/distribution/isqf.py
When running in hybridized form, I'm running into shape inference errors where those comparisons are done.
I added explicit `broadcast_like` in those comparisons to resolve this issue.
* There are other comparisons that may need fixing.
* This might be better fixed upstream as part of mxnet.
=> Fix: use broadcast_lesser in place of comparisons in ISQF

src/gluonts/dataset/loader.py, src/gluonts/model/seq2seq/_forking_estimator.py, src/gluonts/mx/model/estimator.py, test/dataset/test_data_loader.py
Addresses #1928 
Fixes multiprocessing iterator so that it can be iterated over multiple times. This requires a little more synchronization between workers and main process, but it’s pretty simple.
To do:
=> Add multiprocessing to validation data loader

src/gluonts/model/estimator.py, test/model/npts/test_model.py
It appears the `DummyEstimator.train` still expected `validation_dataset` which conflicts with `Estimator` and broke inheriting dummy classes if `validation_data` was passed.
=> Fix dummy estimator

src/gluonts/mx/distribution/transformed_distribution.py
While using `TransformedDistribution` with series of `AffineTransformation` bijection, I get the following `Autograd` error.
`MXNetError: Check failed: AGInfo: :IsNone(*output): Inplace operations (+=, -=, x[:]=, etc) are not supported when recording with autograd.` 
at
`File "/Users/kapooshu/miniconda3/envs/tsf-uds/lib/python3.7/site packages/gluonts/mx/distribution/transformed_distribution.py", line 158, in log_prob
lp -= sum_trailing_axes(F, ladj, self.event_dim - t.event_dim)`
In this PR, I removed this Inplace operation.
**Please tag this pr with at least one of these labels to make our …
=> Fixed autograd inplace operations error in Transformed Distribution

src/gluonts/mx/distribution/beta.py, src/gluonts/mx/distribution/distribution_output.py, src/gluonts/mx/distribution/gamma.py, src/gluonts/mx/distribution/gaussian.py, src/gluonts/mx/distribution/genpareto.py, src/gluonts/mx/distribution/inflated_beta.py, src/gluonts/mx/distribution/laplace.py, src/gluonts/mx/distribution/logit_normal.py, src/gluonts/mx/distribution/neg_binomial.py, src/gluonts/mx/distribution/poisson.py, src/gluonts/mx/distribution/student_t.py
*Description of changes:* The output of `softplus` can easily be zero or negative on CPU (see also #1894), so enforcing positive outputs by adding a small constant is fragile and can potentially give nans in the loss computation (when log or reciprocal is taken). In the case of student-t for example, no safety margin was even added (see code). This fix ensures that distribution parameters which are required to be positive are in fact positive (>= machine epsilon, for the floating point type being used).
**Please tag this pr with at least one of these labels to make our release process faster:** BREAKING, new feature, bug fix, other change, dev …
=> Fix: Hard threshold positive distribution parameters

src/gluonts/model/seq2seq/_mq_dnn_estimator.py, src/gluonts/mx/block/quantile_output.py, test/model/seq2seq/test_quantile_loss.py, test/mx/block/test_quantile_loss.py
*Issue #, if available:* Fixes #1944
*Description of changes:* #1693 modified the behavior of `QuantileOutput` causing #1944. This PR recovers the former behavior, and splits the "incremental quantiles" case into a separate `IncrementalQuantileOutput` class (instead of having the `is_iqf` option). Surrounding changes to related classes are also there (projection layers used, MQ-DNN models).
This is a bit of a sensible change, so I'd like to add tests. Opening nevertheless to get early feedback @dcmaddix @youngsuk0723 
I also think that `IncrementalQuantileOutput` should avoid sorting the quantile levels, or at least allow the projection layer to sort them back, which would make the interface clearer: if I construct the class with quantile levels `[0.9, 0.1]`, maybe I expect the projection …
=> Breaking: Split incremental quantile output into separate class

docs/tutorials/forecasting/howto_pytorch_lightning.md, examples/example_binned_pareto.py, src/gluonts/torch/distributions/__init__.py, src/gluonts/torch/distributions/binned_uniforms.py, src/gluonts/torch/distributions/distribution_output.py, src/gluonts/torch/distributions/generalized_pareto.py, src/gluonts/torch/distributions/isqf.py, src/gluonts/torch/distributions/mqf2.py, src/gluonts/torch/distributions/piecewise_linear.py, src/gluonts/torch/distributions/spliced_binned_pareto.py, src/gluonts/torch/model/deepar/estimator.py, src/gluonts/torch/model/deepar/module.py, src/gluonts/torch/model/mqf2/estimator.py, src/gluonts/torch/model/mqf2/module.py, src/gluonts/torch/model/simple_feedforward/estimator.py, src/gluonts/torch/model/simple_feedforward/module.py, test/torch/distribution/test_torch_piecewise_linear.py, test/torch/model/test_mqf2_modules.py, test/torch/modules/test_torch_distribution_inference.py
*Description of changes:* This puts distribution and output layer definitions closer together, to avoid issues like the circular dependencies that #1962 ran into. Also: shortening distribution-related import paths.
=> Breaking: reorg torch package, shorten import paths

src/gluonts/torch/model/deepar/module.py
The num_parallel_samples is never used.
=> Fix: use of num_parallel_samples in deepAR

src/gluonts/torch/model/deepar/lightning_module.py
pytorch min return min and min_indicies so only use the min
=> Fix: torch DeepAR observed indicator in multivariate case

src/gluonts/info.py
Simple CLI tool to get infos about gluonts installation:
```sh
$ python -m gluonts.info version
0.dev0+g027df66f
```
=> Add info cli.

docs/tutorials/forecasting/extended_tutorial.md, docs/tutorials/forecasting/quick_start_tutorial.md, docs/tutorials/hyperparameter_tuning/hp_tuning_with_optuna.md, docs/tutorials/mxnet_models/trainer_callbacks.md
* Speed up tutorials by disabling regeneration of the datasets, and using `m4_hourly` everywhere so that it's downloaded once
* Fix sentences where needed
=> Documentation: fix and speed up tutorials

src/gluonts/model/rotbaum/_predictor.py, src/gluonts/model/rotbaum/_preprocess.py
I added support for related time series (RTS) that are accessible in the forecast horizon. I changed the syntax so that 'feat_dynamic_real' now means "long" RTS (having info in the forecast horizon), and 'past_feat_dynamic_real' refers to "short" RTS (having no info in the forecast horizon). This is a change of syntax from before in the sense that before there was only support for 'feat_dynamic_real', which was assumed to be short, not long.
=> Added support of "long" RTS, making short RTS be "past_feat_dynamic_real"

src/gluonts/dataset/util.py
This function is not used, and there is `itertoolz.merge_with`
which offers the same functionality`.
=> Remove `dct_reduce`.
