gluonts/core/_base.py
gluonts/core/component.py
gluonts/core/exception.py
gluonts/core/log.py
gluonts/core/serde.py

Add API documentation to the `core` package

---

README.md

fix links to code in the readme

---

test/distribution/test_distribution_inference.py

Stabilize test for deterministic_l1 (use smaller variance)

---

src/gluonts/dataset/artificial/_base.py
src/gluonts/dataset/artificial/generate_synthetic.py

Made metadata, train and test methods properties in artificial datasets so they match the api of the repository datasets. Also, added the prediction length in metadata.

fix artificial dataset

---

src/gluonts/support/util.py
src/gluonts/trainer/_base.py

*Issue #, if available:* #75 
According to [this](https://docs.python.org/3/library/tempfile.html#tempfile.TemporaryDirectory) and [this](https://stackoverflow.com/questions/847850/cross-platform-way-of-getting-temp-directory-in-python), this PR should result in the same behavior on Linux/macOS, but fix the Windows case.

Fix temporary dir paths

---

evaluations/README.md
evaluations/generate_evaluations.py
evaluations/show_results.py
src/gluonts/dataset/repository/datasets.py
src/gluonts/evaluation/_base.py
src/gluonts/evaluation/backtest.py
src/gluonts/trainer/_base.py

add evaluation table of models and tools to generate it

---

src/gluonts/distribution/neg_binomial.py
src/gluonts/distribution/piecewise_linear.py
src/gluonts/distribution/uniform.py
test/distribution/test_distribution_output_shapes.py

*Issue #, if available:* #91 
There was some shape problem with the NegativeBinomialOutput class. I added a test for all Output classes, and fixed a couple of related issues.

Fix bugs in distributions

---

src/gluonts/__init__.py

Bump version to 0.2.0dev

---

requirements.txt

We use features not available in 1.3.0.

Bumped required mxnet version.

---

.travis.yml

Added travis for PyPi deployments.

---

.travis.yml

Updating the password using `--pro`

Updated travis password.

---

test/distribution/test_distribution_inference.py

fix mypy complaints

---

README.md

Added link to Arxiv paper

---

README.md

Add bibtex entry to README

---

src/gluonts/dataset/artificial/_base.py
src/gluonts/distribution/bijection.py
src/gluonts/distribution/binned.py
src/gluonts/distribution/distribution.py
src/gluonts/distribution/gaussian.py
src/gluonts/distribution/laplace.py
src/gluonts/distribution/mixture.py
src/gluonts/distribution/student_t.py
src/gluonts/distribution/transformed_distribution.py
src/gluonts/distribution/uniform.py
src/gluonts/support/util.py
src/gluonts/testutil.py
test/dataset/artificial/test_complex_seasonal.py
test/distribution/test_distribution_sampling.py
test/distribution/test_mixture.py
test/distribution/test_transformed_distribution.py
test/support/test_util.py

This includes a `cdf` method for (some of) the distribution.
Also fixes a couple of bugs in distributions.

include cdf method in distribution

---

src/gluonts/distribution/piecewise_linear.py
test/distribution/test_piecewise_linear.py

rename `._cdf -> .cdf` method for splines

rename cdf method for splines

---

src/gluonts/evaluation/_base.py
src/gluonts/model/forecast.py
src/gluonts/model/seq2seq/_forking_estimator.py
src/gluonts/model/seq2seq/_seq2seq_estimator.py
test/model/test_forecast.py

Moved `parse_quantile_input` to `Quantile` class which
provides explicit methods.

Refactored quantile parsing.

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md

github templates from gluonnlp

github templates

---

.gitignore

Revert "ignoring version.py"

---

src/gluonts/runtime_params.py
src/gluonts/transform.py

include safety check that catches infinite loops in transformations

include safety check that catches infinite loops in transformations

---

MANIFEST.in

Added `MANIFEST.in`.

---

requirements-docs.txt

Bump-up the mxtheme requirement listed in `requires-docs.txt` to a newer version which is also available in PyPi.

Update to PyPi-based mxtheme version 0.3.*

---

src/gluonts/model/npts/__init__.py
src/gluonts/model/npts/_estimator.py
src/gluonts/model/npts/_model.py
src/gluonts/model/npts/_predictor.py
src/gluonts/model/npts/_weighted_sampler.py
test/model/test_models.py
test/model/test_npts.py

Bring back the NPTS estimator.

Add NPTS estimator

---

src/gluonts/dataset/common.py
test/dataset/test_loader.py

*Description of changes:* Changing `ProcessSF2Dict` into `ProcessDataEntry`, plus removing a useless transformation block used in it.

Minor code cleanup

---

src/gluonts/gp/gaussian_process.py
src/gluonts/model/gp_forecaster/_estimator.py
src/gluonts/model/gp_forecaster/_network.py

This suppresses `DeprecationWarning`s

Fixed doc-strings using `\sigma` to use raw-strings.

---

src/gluonts/dataset/artificial/_base.py

custom seasonality for complex seasonal dataset

---

examples/anomaly_detection.py
src/gluonts/distribution/transformed_distribution.py
src/gluonts/model/deepar/_network.py
src/gluonts/model/estimator.py
src/gluonts/model/forecast.py
test/distribution/test_lds.py
test/model/test_deepar_auxiliary_outputs.py

Allows to get access to distribution on DeepAR trainining network and add a minimal example to do anomaly detection.

Anomaly detection

---

src/gluonts/model/forecast.py

Added process method to forecast.Config.

---

CONTRIBUTING.md

Add some documentation on development environment setup using conda virtual environment and pip 
for `gluon-ts`. Also describes how to get the source code in pull requests (PRs) onto your local machine for code-review of pull-requests. There are 2 options given for PRs, in scipy they opted to use the second option w/only checkout of individual branches. Here I give you the choice of which (or both) to choose. 

Contrib 1: add documentation for dev setup and code review of PRs

---

src/gluonts/model/forecast.py

The solution in #166 does not allow to override the logic for a specific `Forecast` subclass. To do that, the processing logic should be attached to the `Forecast` class instead of `Config`.
The method is now also renamed to the more descriptive `as_json_dict`.

Move `forecast.Config.process` method to `Forecast` class

---

ci/prepare_clean_env.sh
src/gluonts/model/prophet/__init__.py
src/gluonts/model/prophet/_estimator.py
src/gluonts/model/prophet/_predictor.py
test/model/prophet/test_prophet.py

Adds support for dynamic real valued features and some tests to `Prophet`. 

Minor fixes in the ProphetPredictor

---

ci/jenkins/build_steps.groovy

enable timeout for all build steps.

[CI] enable timeout

---

setup.py
src/gluonts/dataset/jsonl.py
src/gluonts/model/forecast.py
src/gluonts/model/prophet/_predictor.py
src/gluonts/shell/__main__.py
src/gluonts/shell/sagemaker/params.py
src/gluonts/testutil.py
test/model/test_backtest.py

Minor fixes.

---

conftest.py
src/gluonts/shell/__main__.py

Fixup of shell.

---

src/gluonts/shell/__main__.py

Re-added locate for Forecaster detection.

---

src/gluonts/core/log.py
src/gluonts/shell/__main__.py
src/gluonts/shell/sagemaker/__init__.py
src/gluonts/shell/sagemaker/path.py
src/gluonts/shell/serve/__init__.py
src/gluonts/shell/train.py

- Add proper documentation strings.
- Fix the printed script name in help output.
- Add a `force-static` train parameter that forces the creation of a static predictor from the expected model location.

More shell fixes

---

src/gluonts/evaluation/_base.py
src/gluonts/model/forecast.py

Unified quantile object usage.

---

src/gluonts/shell/sagemaker/__init__.py
src/gluonts/shell/sagemaker/path.py
src/gluonts/shell/train.py

The goal is to be closer to the metrics generated by SageMaker DeepAR.

Refactored metric printing.

---

src/gluonts/model/deepar/_estimator.py

*Description of changes:* The current docstring for `DeepAREstimator` is out of sync, this PR puts it back in sync with the code.

fix deepar docstring

---

src/gluonts/shell/serve/__init__.py

Configurable inference server address and timeout

---

src/gluonts/model/npts/_model.py
src/gluonts/model/npts/_predictor.py

*Issue #, if available:* #197 (partially)
*Description of changes:* Address complaints from pandas on NPTS.

Fix pandas warnings on npts

---

src/gluonts/evaluation/_base.py

*Issue #, if available:* #197 (partially)
*Description of changes:* Some warnings are raised by numpy when
1. masked arrays with masked elements are compared (e.g. using <, >=, and so on)
2. the `np.ma.masked` value is converted to `nan` with `float`
This PR addresses 1 by wrapping metrics computation around a context manager (as suggested [here](https://stackoverflow.com/a/25354869/387656)), and 2 by using an `if` instead of `float` for casting.

Fix docstrings and numpy warnings

---

test/model/prophet/test_prophet.py

Better names for the Prophet tests

---

examples/persist_model.py

The intention of this example is to show how to serialize/deserialize and therefore the deserialized predictor should be used.

fix mistake in example

---

src/gluonts/shell/sagemaker/__init__.py

add one more legacy frequency key

---

requirements/requirements-setup.txt

Bump up `setuptools_scm` version

---

docs/install.rst

minor fix to installation docs

---

src/gluonts/model/forecast.py

Now quantiles are a dict with quantile-name -> values.
/cc @lovvge

Commit quantile output format.

---

src/gluonts/model/forecast.py
src/gluonts/shell/serve.py
src/gluonts/shell/train.py

Unify logging format

---

docs/install.rst
env/cpu/py3-master.yml
env/cpu/py3.yml
env/gpu/py3-master.yml
env/gpu/py3.yml

Align MXNet version range in conda and docs

---

src/gluonts/dataset/common.py
src/gluonts/evaluation/backtest.py

Fix one type hint and replace an assertion with a proper Exception since it's not limited to debugging use cases.

Minor code style fixes

---

src/gluonts/shell/serve.py

Added throughput logging for inference.

---

src/gluonts/model/trivial/mean.py
src/gluonts/support/pandas.py
test/shell/test_shell.py

Adapted mean predictor to use random samples.

---

src/gluonts/model/predictor.py
src/gluonts/model/trivial/mean.py
src/gluonts/shell/sagemaker/__init__.py

Fallback predictor

---

src/gluonts/model/predictor.py
src/gluonts/model/trivial/constant.py
src/gluonts/model/trivial/mean.py
src/gluonts/support/pandas.py

Made `fallback` process-safe. Added ConstantValuePredictor.

---

src/gluonts/shell/__main__.py

Adding failure information to failure file.

---

src/gluonts/shell/__main__.py

Shell failure

---

src/gluonts/shell/serve.py

fix the empty item list

---

src/gluonts/block/decoder.py
src/gluonts/model/canonical/_network.py
test/model/test_models.py

fix the shape error of the canonical network

---

src/gluonts/dataset/common.py
test/dataset/test_common.py

Added rollback for business day freq.

Fix yearly freq in process start field.

---

src/gluonts/distribution/multivariate_gaussian.py
src/gluonts/support/linalg_util.py

*Issue #, if available:* #160 
*Description of changes:* See discussion in #160.

fix issue with MultivariateGaussianOutput

---

env/cpu/py3-master.yml
env/cpu/py3.yml
env/gpu/py3-master.yml
env/gpu/py3.yml

update sphinx to 1.7.9

---

src/gluonts/model/predictor.py
src/gluonts/model/trivial/constant.py
src/gluonts/model/trivial/identity.py
src/gluonts/model/trivial/mean.py
src/gluonts/transform.py

*Issue #, if available:* #263 

make item_id field uniform across predictors

---

docs/examples/extended_forecasting_tutorial/extended_tutorial.md

*Issue #, if available:* fixes #260 

fix mistake in notebook

---

src/gluonts/model/deep_factor/RNNModel.py
src/gluonts/model/deep_factor/__init__.py
src/gluonts/model/deep_factor/_estimator.py
src/gluonts/model/deep_factor/_network.py

Minor changes to pull request https://github.com/awslabs/gluon-ts/pull/259
Paper: https://arxiv.org/pdf/1905.12417.pdf
- Updated example code to get metrics approx 0.26 on electricity
- Corrected file paths
- Corrected minor documentation shapes

Deep Factor [WIP]

---

src/gluonts/dataset/common.py
test/dataset/test_common.py

Fixed ProcessStartField.

---

.dockerignore
Dockerfile
setup.py

Added Dockerfile.

---

docs/bibliography.rst
evaluations/generate_evaluations.py
src/gluonts/distribution/lds.py
src/gluonts/model/deepstate/__init__.py
src/gluonts/model/deepstate/_estimator.py
src/gluonts/model/deepstate/_network.py
src/gluonts/model/deepstate/issm.py
src/gluonts/time_feature/lag.py

Implementation for the paper: https://papers.nips.cc/paper/8004-deep-state-space-models-for-time-series-forecasting

Bring deep state to gluon-ts

---

src/gluonts/distribution/neg_binomial.py
test/distribution/test_negative_binomial.py

*Issue #, if available:* #287 

fix numerical issue with negative binomial distribution

---

src/gluonts/block/rnn.py
src/gluonts/model/canonical/_estimator.py
src/gluonts/model/deep_factor/RNNModel.py
src/gluonts/model/deep_factor/_estimator.py
src/gluonts/model/deep_factor/_network.py
src/gluonts/model/gp_forecaster/_estimator.py
src/gluonts/model/gp_forecaster/_network.py
test/gp/test_jitter.py
test/model/test_models.py
test/model/test_models_synthetic.py

https://github.com/awslabs/gluon-ts/issues/290
- Added documentation for the DeepFactorEstimator
- Added the DeepFactorEstimator to test/models/test_models.py and test/models/test_models_synthetic.py
-- TODO: test_serialize() is not passing muted for now
- Minor code cleanup and variable renaming 

Added documentation and tests for Deep Factor

---

src/gluonts/model/forecast.py
test/model/test_forecast.py

Include `DistributionForecast` and make plot work for all `Forecast` objects.

include DistributionForecast and make plot generic

---

src/gluonts/model/predictor.py

#313 
Manage mxnet context when deserializing predictors and don't swallow error messages.

Manage mxnet context when deserializing predictors

---

src/gluonts/model/deepstate/_network.py
src/gluonts/model/deepstate/issm.py

*Issue #, if available:* #337 
*Description of changes:* The shape of the samples tensor is fixed, and some room is made for potentially handling linear dynamical systems with multivariate output.

Fix DeepState samples tensor shape

---

docs/conf.py

*Description of changes:* Some intersphinx-related file seems to have changed URL for mxnet, and our CI cannot build docs anymore. This PR is an attempt to pointing sphinx to the right URL.

attempt to fix docs build

---

.github/workflows/pythonpackage.yml

Adding tests through github action.

---

test/model/test_models_synthetic.py

Increased test timeout.

---

.github/CODEOWNERS

I want to start to organise our code-base a bit more.
Code-owners allows us to have people assigned to certain parts of gluon-ts automatically.

Started adding code-owners.

---

src/gluonts/distribution/binned.py

small fix for binned distribution

---

requirements/requirements-test.txt
test/model/test_models.py

Marked test as flaky.

---

.github/workflows/black.yml
.github/workflows/pythonpackage.yml

Actions run on pull-requst event.

---

src/gluonts/core/serde.py
test/core/test_serde.py

Added pd.Timestamp to serde.

---

CONTRIBUTING.md

*Issue #, if available:* -
The development setup guide was missing some steps required to correctly set up the project.

Improve dev setup instructions

---

src/gluonts/core/component.py
src/gluonts/model/npts/_model.py

small fixes

---

src/gluonts/distribution/__init__.py
src/gluonts/distribution/distribution_output.py
src/gluonts/evaluation/_base.py
src/gluonts/model/forecast.py

Some minor fixes in different places.

some small fixes

---

src/gluonts/dataset/artificial/recipe.py

Some small fixes to recipe package

---

test/distribution/test_distribution_sampling.py

Increase number of samples for testing distributions to make tests more reliable.

Increase number of samples for testing distributions

---

ci/jenkins/Jenkinsfile_py3-master_gpu_doc

Stopped CI from posting doc-build links to PRs.

---

src/gluonts/distribution/binned.py
test/distribution/test_distribution_output_shapes.py

There was a Validation error in the LowrankMultivariateGaussianOutput class: "transforms value is not a valid list"
Write transformation as a list

bug multivariate gaussian

---

src/gluonts/model/deep_factor/_estimator.py
src/gluonts/model/deepar/_estimator.py
src/gluonts/model/transformer/_estimator.py

Fix for assertions regarding cardinalities and embedding dimensions.

Bug fix: assert all elements in the list are True.

---

.github/ISSUE_TEMPLATE/question.md
.github/workflows/black.yml

add question template

---

ci/prepare_clean_env.sh

Explicitly specify CUDA version in path

---

src/gluonts/distribution/dirichlet.py

*Issue #, if available:* #424 

Minor fix to Dirichlet sampling

---

README.md

Update installation instructions in README.md 

---

examples/benchmark_m4.py
examples/evaluate_model.py
examples/persist_model.py
src/gluonts/model/forecast_generator.py
src/gluonts/model/simple_feedforward/_estimator.py
test/model/test_models_synthetic.py

*Description of changes:* some changes following #421 

Remove some occurrences of num_eval_samples

---

setup.py

*Issue #, if available:* Fixes #85

Fixes to setup.py to make it work on Windows

---

src/gluonts/core/serde.py
test/core/test_serde.py

Fix escaping of string in serde.dump_code.

---

.github/workflows/pythonpackage.yml
requirements/requirements.txt
test/shell/test_shell.py

*Issue #, if available:* if working, this fixes #80 

Added windows to CI python build.

---

test/distribution/test_distribution_sampling.py

In some cases np.allclose fails.

Added flaky to test_multivariate_sampling.

---

.github/workflows/docs.yml
src/gluonts/dataset/multivariate_grouper.py

Added docs to Actions.

---

src/gluonts/model/predictor.py

*Description of changes:* the warning seemed to be in the wrong class

Move serialization warning to RepresentableBlockPredictor

---

src/gluonts/model/forecast.py

Added median as alias for p50 to Forecast.

---

src/gluonts/model/deepar/_network.py

*Description of changes: Removed unused static method in DeepARNetwork class.

removed unused static method in DeepARNetwork

---

requirements/requirements.txt
src/gluonts/core/component.py
src/gluonts/core/serde.py
src/gluonts/dataset/common.py
src/gluonts/model/estimator.py
src/gluonts/model/forecast.py

Updated pydantic to version 1.

---

src/gluonts/evaluation/_base.py
src/gluonts/evaluation/backtest.py
src/gluonts/model/forecast.py
test/evaluation/test_evaluator.py

Second pull request for the multivariate model. This ports over the ability of the `MultivariateEvaluator` to evaluate on aggregates of the target and forecast (the aggregates should usually be more consistent in a multivariate model than in an univariate model). 

Added aggregation functionality to MultivariateEvaluator

---

.github/workflows/mxnet-nightly.yml

Added mxnet nightly builds.

---

test/model/seq2seq/test_forking_sequence_splitter.py

Remove warning in tests.

---

requirements/requirements-docs.txt

Refined doc requiremnents; using sphinx 2.

---

src/gluonts/evaluation/_base.py

forcecast -> forecast

---

src/gluonts/distribution/__init__.py
src/gluonts/distribution/bijection.py
src/gluonts/distribution/box_cox_transform.py
test/distribution/test_distribution_inference.py
test/distribution/test_distribution_shapes.py

tranform -> transform

---

README.md

Try to avoid user problems such as https://github.com/apache/incubator-mxnet/issues/16924

Specify --upgrade in README.md install example

---

src/gluonts/dataset/repository/_gp_copula_2019.py
src/gluonts/dataset/repository/datasets.py

Added datasets from the GP Copula paper to the GluonTS master repository. Also adds categorical features that where missing in the original fork.
Paper link: https://arxiv.org/abs/1910.03002

Added GP Copula datasets

---

test/distribution/test_distribution_inference.py

fix typo in test

---

src/gluonts/dataset/common.py

Changed FileDataset to be more easily inheritable.

---

test/model/test_forecast.py

fixed forecast test assert string

---

src/gluonts/dataset/common.py

Removed unused function rollback.

---

src/gluonts/distribution/__init__.py
src/gluonts/distribution/beta.py
test/distribution/test_distribution_inference.py
test/distribution/test_distribution_methods.py
test/distribution/test_distribution_output_shapes.py
test/distribution/test_distribution_sampling.py
test/distribution/test_distribution_shapes.py
test/distribution/test_issue_287.py

This is related to Issue https://github.com/awslabs/gluon-ts/issues/467.

Beta distribution implemented.

---

src/gluonts/distribution/beta.py
src/gluonts/distribution/gamma.py
src/gluonts/distribution/neg_binomial.py

Fixed distribution invalid sampling issues. Added machine epsilon as minimal delta.

Fixed distribution sampling issues.

---

src/gluonts/nursery/sagemaker_sdk/estimator.py

Quickfix for SageMaker SDK.

---

pytest.ini
test/distribution/test_distribution_inference.py
test/distribution/test_mixture.py
test/model/test_deepvar.py
test/model/test_models.py
test/model/test_models_synthetic.py

Removed timeouts from tests.

---

src/gluonts/dataset/repository/_gp_copula_2019.py

fixed taxi dataset cardinality

---

src/gluonts/model/simple_feedforward/_network.py

Fixed docstring in simple feed forward.

Fixed docstring in simple feed forward.

---

README.md

Add link to master docs, add docs badges

---

docs/examples/extended_forecasting_tutorial/extended_tutorial.md
src/gluonts/dataset/common.py

Enhanced error message for input time-series fields.

---

Dockerfile

*Issue #, if available:* Fixes #550 

Fix Dockerfile to use Python 3.7.

---

test/model/test_models.py

*Issue #, if available:* Attempt at fixing #573 

disabling test for ensemble nbeats because of timeouts

---

requirements/requirements-setup.txt
src/gluonts/evaluation/backtest.py
src/gluonts/model/deepvar/_estimator.py
src/gluonts/model/gpvar/_estimator.py

Updated black.

---

requirements/requirements-setup.txt
src/gluonts/core/serde.py
src/gluonts/shell/serve/app.py

Mypy update

---

src/gluonts/dataset/loader.py
src/gluonts/dataset/util.py
src/gluonts/model/predictor.py
src/gluonts/transform/_base.py

Refactored DataLoader.

---

src/gluonts/model/forecast.py
test/model/test_forecast.py

*Issue #, if available:* fixes #642 

fix forecast index bug, add test

---

src/gluonts/distribution/binned.py
src/gluonts/distribution/dirichlet.py
src/gluonts/distribution/distribution.py
src/gluonts/distribution/mixture.py
src/gluonts/distribution/multivariate_gaussian.py
src/gluonts/distribution/piecewise_linear.py
src/gluonts/distribution/transformed_distribution.py
test/distribution/test_distribution_slice.py

Support numpy like slicing of distributions.

support slicing of distributions

---

src/gluonts/model/n_beats/_network.py

Fixes issue https://github.com/awslabs/gluon-ts/issues/629.
Just named all the layers in the network explicitly.

N beats bugfix.

---

src/gluonts/trainer/_base.py

log epochs in trainer

---

examples/anomaly_detection.py

The `examples/anomaly_detection` fails to create plots using pandas v1.0 in #576 due to backward incompatible changes to pandas.

Fix incompatible date_range and matplotlib register in pandas v1.0

---

examples/m5_gluonts_template.ipynb

This is an initial draft of a template for using GluonTS-based tooling to participate in the M5 forecasting competition.

Add M5 template

---

src/gluonts/trainer/_base.py
src/gluonts/trainer/learning_rate_scheduler.py

Improve trainer handling of learning rate scheduling and logging

---

src/gluonts/dataset/loader.py
src/gluonts/dataset/util.py

Prevent data from be cached in DataLoader.

---

docs/examples/extended_forecasting_tutorial/extended_tutorial.md

Remove hidden _base from the extended tutorial

---

src/gluonts/evaluation/_base.py
test/evaluation/test_evaluator.py

Add MAPE to evaluator

---

setup.py

fixes pytest when running via setup.py

fix setup for multiprocessing

---

src/gluonts/dataset/parallelized_loader.py
test/model/test_item_id_info.py

*Issue #, if available:* Fixes #758 

Fix stack function

---

.github/workflows/docs.yml
.github/workflows/mxnet_nightly.yml
.github/workflows/style_checks.yml
.github/workflows/tests.yml
test/model/test_item_id_info.py

*Description of changes:* Fixes a missing header, adjust the style checks workflow to check license headers as well. Other minor changes to the workflows.

fix license header, update workflows

---

.github/workflows/mxnet_nightly.yml

*Issue #, if available:* fixes #717 

Update workflows against nightly mxnet

---

.github/workflows/test_release_unix_nightly.yml
.github/workflows/test_release_win32_nightly.yml

*Issue #, if available:* fixes #821
Added new requirements that was added since Gluon-TS release V 0.4.3 to the nightly runs

Fix nightly tests of release

---

.github/workflows/mxnet_nightly.yml

*Issue #, if available:* #826
Added " " around pip install statement allowing dependencies to be properly installed
Fixes #826

Fix mxnet nightly tests

---

src/gluonts/trainer/__init__.py
src/gluonts/trainer/_base.py
src/gluonts/trainer/model_averaging.py
test/trainer/test_model_averaging.py

Model averaging
Averaging of best models (based on best epochs) during training. The weight of each model is either `1/N` or proportional to the metric value (better metric value more weight).

Model averaging

---

src/gluonts/gluonts_tqdm.py

Fixed disabling of tqdm.

---

src/gluonts/model/seq2seq/_forking_estimator.py
src/gluonts/model/seq2seq/_transform.py

* fixing edge case of prediction length 1
* and some defaults

MQCNN fixes

---

src/gluonts/dataset/split/splitter.py
test/dataset/split/test_split.py

Fix to_time_series_item in splitter.

---

src/gluonts/transform/convert.py

Simplified AsNumpyArray.

---

src/gluonts/model/estimator.py
src/gluonts/model/wavenet/_estimator.py
src/gluonts/transform/_base.py

Removed unused `Transformation.estimate`.

---

src/gluonts/shell/README.md

Added README to shell.

---

ci/prepare_clean_env.sh
setup.py

Docs requirements

---

README.md

Update bibliographic references in README

---

src/gluonts/mx/distribution/mixture.py
test/distribution/test_mixture.py

Corrected the formula of the stddev of the MixtureDistribution.

Corrected the formula for the stddev of the MixtureDistribution.

---

src/gluonts/model/r_forecast/_predictor.py

Fix pathes in R for Windows.

---

src/gluonts/dataset/artificial/_base.py
src/gluonts/dataset/common.py
test/dataset/test_loader.py

Removed TimeSeriesItem.

---

src/gluonts/evaluation/backtest.py

*Description of changes:* The `backtest_metrics` function was using multiprocessing options the wrong way (using it on the `InferenceDataLoader`, only used for hybridization purposes, instead of the `train` method of estimators).

fix multiprocessing in backtest function

---

src/gluonts/dataset/jsonl.py
test/dataset/test_jsonl.py

Added support for gzipped files.

---

src/gluonts/shell/serve/app.py

Fix batch-transform case, where request is empty.

---

src/gluonts/model/forecast.py

Default QuantileForecast.mean to p50.

---

src/gluonts/model/simple_feedforward/_estimator.py
src/gluonts/model/simple_feedforward/_network.py

Add nan support to simple feed-forward model

---

src/gluonts/shell/__main__.py
src/gluonts/shell/serve/__init__.py
src/gluonts/shell/serve/app.py
src/gluonts/shell/util.py

Added timeout option for batch requests.

---

src/gluonts/shell/sagemaker/__init__.py

Make TrainEnv `path` argument explicit.

---

requirements/requirements.txt

*Issue, if available:*
- Pandas 1.1 introduces breaking changes.
- limited pandas version to `<=1.1`
*Fixes*
- https://github.com/awslabs/gluon-ts/issues/965
- https://github.com/awslabs/gluon-ts/issues/958
- https://github.com/awslabs/gluon-ts/issues/959

Fix pandas requirement.

---

requirements/requirements.txt

* Fix pandas requirement.
* Fixing formatting issue.

Backport: Fix pandas requirement.

---

src/gluonts/evaluation/_base.py
src/gluonts/model/n_beats/_network.py
src/gluonts/model/naive_2/_predictor.py
src/gluonts/model/r_forecast/_predictor.py
src/gluonts/model/seasonal_naive/_predictor.py
src/gluonts/model/wavenet/_estimator.py
src/gluonts/time_feature/__init__.py
src/gluonts/time_feature/seasonality.py
test/evaluation/test_evaluator.py
test/test_sanity.py
test/time_feature/test_seasonality.py

Moved get_seasonality from evaluation to time_feature.

---

src/gluonts/shell/__main__.py
src/gluonts/shell/train.py

*Issue #, if available:* #973 
*Description of changes:* 
- Add missing import statements.
- Change the type of `forecaster` to `GluonEstimator`.

Fix type check. (#973)

---

README.md
docs/examples/basic_forecasting_tutorial/tutorial.md
docs/examples/extended_forecasting_tutorial/extended_tutorial.md
examples/COV19-forecast.ipynb
examples/GluonTS_SageMaker_SDK_Tutorial.ipynb
examples/GluonTS_SageMaker_SDK_Tutorial.md
examples/anomaly_detection.py
examples/benchmark_m4.py
examples/evaluate_model.py
examples/m5_gluonts_template.ipynb
examples/persist_model.py
test/model/deepar/test_deepar_auxiliary_outputs.py
test/model/deepar/test_deepar_smoke.py
test/model/deepvar/test_deepvar.py
test/model/gpvar/test_gpvar.py
test/model/lstnet/test_lstnet.py
test/model/test_item_id_info.py
test/paper_examples/test_axiv_paper_examples.py

Fixed import of mxnet Trainer.

---

src/gluonts/model/simple_feedforward/_network.py

Fix docstrings for SimpleFeedForward 

---

src/gluonts/shell/serve/app.py

Added logging of scored instances for batch-transform.

---

.github/workflows/style_type_checks.yml

*Description of changes:* Adding type checks. This should fail before #1017, and succeed after that is merged.

Add type checks to GitHub workflow

---

src/gluonts/dataset/split/splitter.py
src/gluonts/distribution/lds.py
src/gluonts/evaluation/_base.py
src/gluonts/evaluation/backtest.py
src/gluonts/support/util.py
test/dataset/split/test_split.py
test/model/deepstate/test_deepstate_smoke.py

*Issue #, if available:* fixes #1016 (as well as #1015 once a new version is tagged)

Backports to 0.5.x

---

requirements/requirements.txt

https://github.com/awslabs/gluon-ts/issues/1029
Removing version restriction to avoid conflicting versions on `holidays` package. 

Update holidays version

---

requirements/requirements-extras-anomaly-evaluation.txt
src/gluonts/nursery/anomaly_detection/__init__.py
src/gluonts/nursery/anomaly_detection/supervised_metrics/__init__.py
src/gluonts/nursery/anomaly_detection/supervised_metrics/bounded_pr_auc.py
src/gluonts/nursery/anomaly_detection/supervised_metrics/buffered_precision_recall.py
src/gluonts/nursery/anomaly_detection/supervised_metrics/filters.py
src/gluonts/nursery/anomaly_detection/supervised_metrics/precision_recall_utils.py
src/gluonts/nursery/anomaly_detection/supervised_metrics/segment_precision_recall.py
src/gluonts/nursery/anomaly_detection/supervised_metrics/utils.py
test/nursery/anomaly_detection/supervised_metrics/test_filters.py
test/nursery/anomaly_detection/supervised_metrics/test_precision_recall.py

Add evaluation metrics for anomaly detection

---

.github/workflows/docs.yml
.github/workflows/test_release_unix_nightly.yml
.github/workflows/test_release_win32_nightly.yml
.github/workflows/tests.yml
requirements/requirements-extras-anomaly-evaluation.txt
src/gluonts/nursery/anomaly_detection/supervised_metrics/utils.py

speed labels_to_ranges using numba

---

src/gluonts/nursery/anomaly_detection/supervised_metrics/utils.py

Fix numba warning; mask np.nan labels

---

src/gluonts/core/serde.py
test/core/test_serde.py

Added StateFul to serde.

---

examples/warm_start.py
src/gluonts/mx/trainer/_base.py

include callback in trainer and example for warm starting

---

src/gluonts/time_feature/holiday.py
test/time_feature/test_holiday.py

#1094
`MAX_WINDOW` is too small. E.g. eastern can be 1 year + 34 days apart in two subsequent years.

Fix max window

---

conftest.py
docs/community/devsetup.rst
requirements/requirements-extras-sagemaker-sdk.txt
requirements/requirements-test.txt
src/gluonts/nursery/sagemaker_sdk/estimator.py
test/distribution/test_distribution_sampling.py
test/model/tpp/common.py
test/model/tpp/test_tpp_predictor.py
test/nursery/sagemaker_sdk/test_entry_point_scripts.py
test/test_transform.py

Updated pytest to v5.

---

src/gluonts/evaluation/_base.py
test/evaluation/test_evaluator.py
test/model/tft/test_model.py

#1106
Added custom_eval_fn argument to Evaluator/MultivariateEvaluator class

Fixes awslabs/gluon-ts#1106

---

requirements/requirements.txt
src/gluonts/time_feature/_base.py

*Issue #, if available:* Fixes #1099, related to #965 

Fix pandas compatibility issue and remove version cap

---

src/gluonts/model/predictor.py

Simplify Localizer predictor

---

.travis.yml

Fix travis deployment.

---

src/gluonts/mx/block/scaler.py
test/block/test_scaler.py

Add a MinMax scaler

---

src/gluonts/transform/feature.py
test/test_transform.py

Merge newest commits from master to v0.6.x

Merge newest commits from master for V0.6.1

---

.github/workflows/style_type_checks.yml
src/gluonts/mx/block/scaler.py
src/gluonts/mx/distribution/gamma.py
src/gluonts/mx/distribution/genpareto.py
test/block/test_scaler.py
test/distribution/test_distribution_methods.py

Call style_check and type_check explicitly in actions.

---

examples/run_rolling_forecast_backtest.py
src/gluonts/dataset/rolling_dataset.py

- fixed some minor things about the rolling datasets

fix rolling dataset

---

src/gluonts/transform/_base.py
test/test_transform.py

fix chain method of Transformation

---

src/gluonts/transform/_base.py
test/test_transform.py

Merging of PR: fix chain method of Transformation (#1156)

merge for v0.6.2 release

---

src/gluonts/dataset/repository/_m3.py
src/gluonts/dataset/repository/datasets.py

include m3 dataset

---

src/gluonts/dataset/repository/_m3.py

Some offsets are wrong in the m3 dataset.

fix m3 dataset timestamps

---

src/gluonts/dataset/repository/_m3.py
src/gluonts/dataset/repository/datasets.py
src/gluonts/time_feature/_base.py
src/gluonts/time_feature/lag.py
src/gluonts/time_feature/seasonality.py

introduce quarterly and yearly base frequency

---

REFERENCES.md

add more references

---

src/gluonts/model/naive_2/_predictor.py
src/gluonts/model/npts/_model.py
src/gluonts/model/npts/_predictor.py
src/gluonts/transform/feature.py
test/test_dataset_mutability.py

Merge commits:
- Added item_id to NPTS and Naive2 forecasts (#1173)
- fixes in dataset mutability  (#1171)

Merges for v0.6.3

---

requirements/requirements-test.txt
requirements/requirements.txt
src/gluonts/dataset/common.py
src/gluonts/dataset/jsonl.py
src/gluonts/json.py
test/dataset/test_loader.py

Custom json

---

src/gluonts/torch/component.py
src/gluonts/torch/model/predictor.py
test/torch/model/test_torch_predictor.py

Adds a `__eq__` operator to PyTorchPredictors to have them comparable via `==`.

Add equality operator for PytorchPredictor

---

src/gluonts/torch/model/predictor.py
test/torch/model/test_torch_predictor.py

*Issue #, if available:* partially addresses #1193 

Fix PyTorchPredictor serde

---

src/gluonts/dataset/artificial/ar_p.py
src/gluonts/dataset/artificial/recipe.py
test/dataset/artificial/test_recipe.py

Improvements for data generation
- include ARp process
- more functions in lifted_numpy
- support Length without argument
- support shape/size=(.., 0, ...)
- more operators

Improvements for data generation

---

docs/bibliography.rst
src/gluonts/mx/activation.py
src/gluonts/mx/block/sndense.py
src/gluonts/mx/block/snmlp.py
src/gluonts/mx/distribution/bijection.py
src/gluonts/mx/distribution/iresnet.py
test/activation/test_activations.py
test/distribution/test_flows.py

Here are the the normalizing flow base components, along with iResnet (old PR has been deleted due to branch renaming). Corrections for the previous PR have been applied, with doc types and additional comments.

Initial normalizing flow commit

---

src/gluonts/mx/model/predictor.py
src/gluonts/torch/component.py
src/gluonts/torch/model/predictor.py
test/torch/model/test_torch_predictor.py
test/torch/modules/test_torch_distribution_inference.py

Merge commits:
- PyTorchPredictor serde (#1086)
- Add equality operator for PytorchPredictor (#1190)
- fix pytorch predictor serde (#1194)

Merges for v0.6.4

---

src/gluonts/dataset/artificial/recipe.py
test/dataset/artificial/test_recipe.py

small fix and assertions for ARp

---

.github/workflows/mxnet_nightly.yml
.github/workflows/test_release_unix_nightly.yml
.github/workflows/test_release_win32_nightly.yml

These have been broken for weeks if not months.

Fix nightly workflows

---

.github/workflows/docs.yml
.github/workflows/mxnet_nightly.yml
.github/workflows/style_type_checks.yml
.github/workflows/test_release_unix_nightly.yml
.github/workflows/test_release_win32_nightly.yml
.github/workflows/tests.yml

Use pip 20.2 to force no dep-resolution.

---

README.md

Adding GluonTS talk from ICML and MxNet Day

Update README.md with GluonTS talk

---

src/gluonts/model/seq2seq/_forking_network.py
src/gluonts/mx/block/cnn.py
src/gluonts/mx/block/decoder.py
src/gluonts/mx/block/dropout.py
src/gluonts/mx/block/enc2dec.py
src/gluonts/mx/block/quantile_output.py
src/gluonts/mx/block/regularization.py
src/gluonts/mx/block/snmlp.py
src/gluonts/mx/kernels/_kernel_output.py
src/gluonts/mx/kernels/_periodic_kernel.py
src/gluonts/mx/kernels/_rbf_kernel.py
src/gluonts/testutil/shell.py
src/gluonts/transform/_base.py

Enable mypy in subpackages

---

src/gluonts/dataset/common.py
src/gluonts/shell/serve/__init__.py
src/gluonts/shell/serve/app.py
test/shell/test_shell.py

Add support for forward fields.

---

src/gluonts/core/serde/__init__.py
src/gluonts/core/serde/_compact.py
src/gluonts/core/serde/flat.py
test/core/test_serde_flat.py

Added compact representation for serde.

---

src/gluonts/core/serde/_base.py
src/gluonts/core/serde/_parse.py
src/gluonts/core/serde/_repr.py

Serde cleanup

---

src/gluonts/torch/modules/distribution_output.py
test/distribution/test_mx_distribution_inference.py
test/torch/modules/test_torch_distribution_inference.py

Add distribution output classes for PyTorch, add tests

---

src/gluonts/shell/__main__.py
src/gluonts/shell/sagemaker/nested_params.py
src/gluonts/shell/sagemaker/train.py
test/shell/test_nested_params.py

Shell: Support for nested hyper-parameters.

---

src/gluonts/torch/model/forecast.py

Fix to_sample_forecast method of torch-based DistributionForecast

---

src/gluonts/model/deepvar/_estimator.py
src/gluonts/model/gp_forecaster/_estimator.py
src/gluonts/model/lstnet/_estimator.py
src/gluonts/model/n_beats/_estimator.py
src/gluonts/model/tft/_estimator.py

This is leftover work from #1206 

Fix batch_size in some estimators

---

src/gluonts/model/gpvar/_estimator.py

Fix error in GPVar constructor

---

requirements/requirements.txt
src/gluonts/core/serde/np.py

Fix serde for np.dtype.

---

src/gluonts/core/serde/np.py

* Fix serde for np.dtype. (#1299)

Merges for v0.6.5

---

docs/tutorials/forecasting/howto_pytorch_lightning.md
docs/tutorials/index.rst

Add pytorch tutorial notebook 

---

.github/workflows/test_release_unix_nightly.yml
.github/workflows/test_release_win32_nightly.yml

*Description of changes:* Nightly workflows have been failing because some requirement files are not there in the latest stable version (v0.6.x)

remove missing requirements from nightly workflows

---

src/gluonts/mx/trainer/_base.py

Issue #1313 :
Description of changes:
* Fixing bug that caused dropout to not be called
* Remove unused and dead code halt
The PR is the same than https://github.com/awslabs/gluon-ts/pull/1314 except that I used recent version (I accidentally used one that was from one year ago and the merge was too painful).

fixing bug where dropout was not used, also remove unused halt option

---

src/gluonts/core/serde/_parse.py
src/gluonts/evaluation/_base.py
test/dataset/test_multiprocessing_loader.py

*Issue #, if available:* Fixes #1004 and other issues on Python 3.8.
Tested locally, only the `shell` tests couldn't pass.

Fixes for Python 3.8

---

src/gluonts/evaluation/_base.py
src/gluonts/model/deepstate/issm.py
src/gluonts/model/n_beats/_network.py
src/gluonts/mx/block/quantile_output.py
src/gluonts/mx/distribution/inflated_beta.py
src/gluonts/mx/trainer/_base.py
test/dataset/test_multiprocessing_loader.py
test/distribution/test_inflated_beta.py
test/model/seq2seq/test_quantile_loss.py

Merging:
* Use broadcast_logical_or in inflated_beta (#1226) 
* Fix type error for using quantile_weights and add a proper Pytest (#1231)
* Fixed MASE in N-BEATS: removed redundant factor (#1288)
* Fixing bug where dropout was not used, also remove unused halt option (#1315)
* Fixes for Python 3.8 (#1318)

Merges for v0.6.6

---

src/gluonts/core/settings.py

Added dependency to settings.

---

src/gluonts/core/settings.py

Settings: Declerative support for dependencies.

---

src/gluonts/model/deepstate/_estimator.py
src/gluonts/model/deepstate/issm.py
src/gluonts/time_feature/__init__.py
src/gluonts/time_feature/_base.py
src/gluonts/time_feature/lag.py
src/gluonts/time_feature/seasonality.py
test/nursery/test_autogluon_tabular.py

can now specify any freq="W-..." string for issue #750
just look at the first part of the week freq string

Normalized frequency-name.

---

src/gluonts/mx/model/predictor.py
test/model/lstnet/test_lstnet.py

Fix serialization of lead_time

---

src/gluonts/torch/model/predictor.py

Fix serialization of lead_time in torch predictor

---

src/gluonts/mx/model/predictor.py
src/gluonts/torch/model/predictor.py
test/model/lstnet/test_lstnet.py

Merge commits:
- Added lead_time argument to PyTorchPredictor (#1316)
- Fix serialization of lead_time (#1328)
- Fix serialization of lead_time in torch predictor (#1329)

Merges for v0.6.7

---

requirements/requirements.txt

#959 
Keep pandas 1.0 in the requirements (for now)

keep pandas 1.0

---

src/gluonts/model/rotbaum/_lgb_wrapper.py
src/gluonts/model/rotbaum/_model.py

*Description of changes:* Support for random sampling at fitting time for QRX, and support for **kwargs in QRX and lgb_wrapper fit functions.

Support for random sampling at fitting time for QRX, and support for **kwargs in QRX and lgb_wrapper fit functions.

---

requirements/requirements.txt
src/gluonts/core/component.py
src/gluonts/transform/sampler.py

*Description of changes:* undoing #1115 

Uncap pydantic version and fix related isssues

---

requirements/requirements-extras-autogluon.txt
src/gluonts/nursery/autogluon_tabular/estimator.py
src/gluonts/nursery/autogluon_tabular/example.py
src/gluonts/nursery/autogluon_tabular/predictor.py
test/nursery/test_autogluon_tabular.py
test/torch/modules/test_torch_distribution_inference.py

Allow serialization and deserialization for auto tabular predictor

---

docs/bibliography.rst
src/gluonts/evaluation/metrics.py

Added docstrings for metrics without any and removed broken links.

Add metric docstrings.

---

src/gluonts/time_feature/_base.py

Merge commits:
- fix compatibility for pandas < 1.1 in `time_feature/_base.py` (#1437)

Merges for v0.7.1

---

requirements/requirements-extras-sagemaker-sdk.txt
src/gluonts/time_feature/_base.py

Merge commits:
- fix s3fs ImportError for fsspec by updating the requirement depending on the python version (#1391)
- fix compatibility for pandas < 1.1 in `time_feature/_base.py` (#1437)

Merges for v0.6.8

---

.devtools/license

Make license check slightly less strict.

---

.devtools/license
.gitattributes
setup.py
src/gluonts/__init__.py
src/gluonts/_static_version.py
src/gluonts/_version.py

Use miniver for version resolution.

---

src/gluonts/model/deepvar/_estimator.py

Merge commits:
- Fix get_lags_for_frequency for minute data in DeepVAR (#1455)

Merges for v0.7.3

---

src/gluonts/core/settings.py
test/core/test_settings.py

Fix Settings._inject to check if it can provide the value.

---

src/gluonts/core/settings.py
test/core/test_settings.py

Settings: Support for nested args in _inject.

---

examples/anomaly_detection.py

*Issue #, if available:* Fixes #1505

Fix anomaly detection example

---

src/gluonts/core/settings.py
test/core/test_settings.py

Settings: Fix partial assignment.

---

src/gluonts/model/tft/_estimator.py
src/gluonts/time_feature/__init__.py
src/gluonts/time_feature/_base.py
test/time_feature/test_features.py

Add constant dummy time features to TFT for yearly data

---

src/gluonts/model/deepstate/issm.py

*Description of changes:* Consolidating code after #1518 (cc @borchero I just realized there was this). The change is backward compatible.

Consolidate ZeroFeature from DeepState

---

examples/anomaly_detection.py
src/gluonts/core/settings.py
src/gluonts/dataset/multivariate_grouper.py
src/gluonts/model/tft/_estimator.py
src/gluonts/time_feature/__init__.py
src/gluonts/time_feature/_base.py
test/core/test_settings.py
test/time_feature/test_features.py

Merge commits:
- Fix Settings._inject to check if it can provide the value. (#1501)
- Fix indentation (#1500)
- Fix anomaly detection example (#1515)
- Add constant dummy time features to TFT for yearly data (#1518)

Merges for v0.7.4

---

src/gluonts/core/_base.py
src/gluonts/core/serde/_base.py
test/core/test_serde.py

Serde: Allow encoding of functions and methods.

---

src/gluonts/model/prophet/_predictor.py
test/model/prophet/test_prophet.py

https://github.com/awslabs/gluon-ts/issues/1531

fix ProphetPredictor serialization issue

---

src/gluonts/model/r_forecast/_predictor.py

Add item_id to r forecast predictors

---

.github/workflows/docs.yml
.github/workflows/mxnet_nightly.yml
.github/workflows/style_type_checks.yml
.github/workflows/test_release_unix_nightly.yml
.github/workflows/test_release_win32_nightly.yml
.github/workflows/tests.yml
src/gluonts/core/_base.py
src/gluonts/core/serde/_base.py
src/gluonts/model/prophet/_predictor.py
src/gluonts/model/r_forecast/_predictor.py
src/gluonts/shell/train.py
src/gluonts/shell/util.py
test/core/test_serde.py
test/model/prophet/test_prophet.py

Merge commits:
- Train invoke with (#1530)
- fix ProphetPredictor serialization issue (#1535)
- Add item_id to r forecast predictors (#1537)
- Serde: Allow encoding of functions and methods. (#1519)
- Disable tests on Windows for PRs, fix other workflows (#1525)

Merges for v0.7.5

---

src/gluonts/mx/distribution/neg_binomial.py
src/gluonts/mx/distribution/poisson.py
test/distribution/test_distribution_output_serde.py

*Issue #, if available:* Fixes #1541

Fix serde issue with some distribution output types

---

.github/workflows/flake8.yml
src/gluonts/dataset/artificial/ar_p.py
src/gluonts/dataset/common.py
src/gluonts/evaluation/_base.py
src/gluonts/model/deepar/_network.py
src/gluonts/model/deepvar/_estimator.py
src/gluonts/mx/linalg_util.py
src/gluonts/nursery/autogluon_tabular/predictor.py
src/gluonts/nursery/gmm_tpp/simulation.py
src/gluonts/nursery/spliced_binned_pareto/training_functions.py

flake8 fixes

---

.github/workflows/flake8.yml

Rename flake8 action step.

---

src/gluonts/mx/distribution/neg_binomial.py
src/gluonts/mx/distribution/poisson.py
test/distribution/test_distribution_output_serde.py

Merge commits:
- Fix serde issue with some distribution output types, add test (#1543)

Merges for v0.7.6

---

test/model/r_forecast/test_r_predictor.py

Use the `constant` dataset for tests. Also assert that the forecast error is small.

Improve tests for R methods

---

src/gluonts/model/r_forecast/R/forecast_methods.R
src/gluonts/model/r_forecast/_predictor.py

STL-AR is one more local model used frequently as a baseline to compare local versus global models.
Implementation available in the [seer package](https://rdrr.io/github/thiyangt/seer/src/R/stlar.R) needed to be modified to get desired prediction intervals.
No additional dependencies.
Tests pass. It also ran on `m4_hourly` dataset and gave very good results.

Add STL-AR as one more R baseline model

---

test/torch/modules/test_torch_distribution_inference.py

Mark torch distribution inference tests as flaky

---

src/gluonts/nursery/glide/_partition.py

*Issue #, if available:* #1590

Fix single dispatch register for py36

---

docs/tutorials/forecasting/extended_tutorial.md
docs/tutorials/forecasting/quick_start_tutorial.md
src/gluonts/mx/__init__.py

https://github.com/awslabs/gluon-ts/issues/1196

shallow import for `gluonts.mx` module

---

.github/workflows/pypi.yml

add GitHub workflow for publishing to PyPI for new releases

---

.github/workflows/pypi.yml

Co-authored-by: Eduard Uffelmann <uffeledu@amazon.com>

add GitHub workflow for publishing to PyPI for new releases (#1601)

---

src/gluonts/core/serde/__init__.py

Add serde module doc.

---

src/gluonts/core/serde/__init__.py

Fix location of serde module doc.

---

src/gluonts/dataset/repository/_tsf_reader.py
test/dataset/test_tsf_reader.py

*Issue #, if available:* Fixes #1649

Fix frequency string conversion from ts format, add test

---

src/gluonts/dataset/repository/_lstnet.py
src/gluonts/model/seq2seq/_mq_dnn_estimator.py
src/gluonts/torch/modules/distribution_output.py
test/torch/modules/test_torch_distribution_inference.py

Backports for v0.7.7

---

src/gluonts/dataset/repository/_tsf_reader.py
src/gluonts/model/seq2seq/_mq_dnn_estimator.py
src/gluonts/torch/modules/distribution_output.py
test/dataset/test_tsf_reader.py
test/distribution/test_flows.py
test/torch/modules/test_torch_distribution_inference.py

Backports for v0.8.1

---

src/gluonts/dataset/common.py
test/dataset/test_common.py

Make Dataset runtime-checkable.

---

src/gluonts/torch/distributions/piecewise_linear.py
src/gluonts/torch/modules/loss.py
src/gluonts/torch/modules/piecewise_linear.py
test/distribution/test_torch_piecewise_linear.py

Adding glouonts.torch.piecewise_linear

---

src/gluonts/model/forecast.py
src/gluonts/model/seq2seq/_transform.py
src/gluonts/mx/block/quantile_output.py
src/gluonts/support/util.py
test/support/test_util.py

- Fixing doc build and comments from MQCNN-IQF PR: https://github.com/awslabs/gluon-ts/pull/1693
-  Fix `mean` method for `QuantileForecast`
- Generalize `LinearInterpolation` method for arbitrary points rather than just `quantile_predictions`

Fixing doc build from mqcnn-iqf commit

---

.github/workflows/mxnet_nightly.yml
.github/workflows/test_release_unix_nightly.yml
.github/workflows/test_release_win32_nightly.yml
.github/workflows/tests.yml
README.md
docs/community/devsetup.rst
setup.py

Set minimum Python version to 3.7.

---

REFERENCES.md

overhaul and update to include our most recent publication on time series related topics.

overhaul and update the bibliography page

---

src/gluonts/dataset/artificial/recipe.py
src/gluonts/mx/distribution/transformed_distribution.py
test/model/npts/test_npts.py
test/mx/distribution/test_nan_mixture.py
test/mx/distribution/test_torch_piecewise_linear.py

Use of int/float/object over np.int/float/object for dtype.

---

.github/workflows/docs.yml
.github/workflows/tests.yml
Makefile
docs/md2ipynb.py

Simplify doc build.

---

src/gluonts/nursery/tsbench/README.md

This PR contains a placeholder readme for TSBench, a benchmark of GluonTS forecasting methods that will be published in the coming weeks (via a separate PR).
Merging this PR would to allow for referencing the code with a valid link in the meantime.

Add TSBench to Nursery Folder

---

src/gluonts/model/rotbaum/README_LSF.ipynb
src/gluonts/model/rotbaum/_model.py

*Description of changes:* Added a readme notebook for LSF. 
Also fixed two minor bugs: 
1. In LSF it always attempts to combine the last bin with the penultimate bin. This fails if there is only one bin, so I added a check for that.
2. Previously min_bin_size was off by 1, so that if min_bin_size was 100 then all bins contained at least 101 datapoints. I fixed this.

added a readme notebook for LSF

---

docs/md2ipynb.py

Disable parallel execution of notebooks.

---

test/conftest.py

Fix test collect ignore.

---

src/gluonts/core/component.py

Remove requirement for @validated in from_hyperparameters.

---

src/gluonts/_version.py

Fix _version for cases when git is not installed.

---

src/gluonts/model/predictor.py
src/gluonts/shell/README.md
src/gluonts/shell/__main__.py
src/gluonts/shell/sagemaker/dyn.py
src/gluonts/shell/sagemaker/serve.py
src/gluonts/shell/sagemaker/train.py

Add dynamic code for shell.

---

src/gluonts/dataset/split/splitter.py
test/dataset/split/test_split.py

Fix datesplitter.

---

src/gluonts/core/serde/flat.py
test/core/test_serde_flat.py

Fix serde.flat type handling.

---

src/gluonts/mx/model/predictor.py
src/gluonts/torch/model/predictor.py
src/gluonts/transform/_base.py
src/gluonts/transform/split.py
test/dataset/test_data_loader.py
test/mx/test_transform_equals.py
test/torch/model/test_simple_torch_model.py

*Issue #1192 
*Support equals check on the transformation*
**Please tag this pr with at least one of these labels to make our release process faster:** enhancement

Check equality of transformations.

---

src/gluonts/mx/block/feature.py

Fixed typo in assert statement.
Fixed typo in assert statement.

Update feature.py fix typo

---

.github/workflows/style_type_checks.yml
requirements/requirements-setup.txt
setup.py

Update mypy to 0.910.

---

src/gluonts/dataset/repository/_tsf_datasets.py
src/gluonts/dataset/repository/_tsf_reader.py

*Issue #, if available:* n/a
*Description of changes:* This PR implements two minor (yet important) improvements for datasets from the [Monash Forecasting Repository](https://forecastingdata.org).
**1: TSF Reader**
The `TSFReader` currently uses `glide.imap_unordered` to process the individual lines of the downloaded dataset file. As a result, preprocessing pipelines are nondeterministic which causes a problem if a deterministic order of e.g. test time series is required.
This PR continues to use `glide.imap_unordered`, but passes an additional index to the worker function which enables sorting according to this index after all items have been processed. This way, the dataset is generated in the same way on every invocation.
**2: Generated Keys**
Currently, all time series extracted from …

Fixes for Monash Forecasting Repository datasets

---

.github/workflows/tests-torch.yml

Ignore nursery in torch tests.

---

src/gluonts/time_feature/_base.py

Added QuarterlyBegin time feature

---

src/gluonts/mx/model/estimator.py
src/gluonts/torch/model/deepar/estimator.py
src/gluonts/torch/model/deepar/lightning_module.py
src/gluonts/torch/model/deepar/module.py
src/gluonts/torch/model/estimator.py

Fix typing issues in torch estimators, update base estimators docstrings

---

src/gluonts/model/transformer/_estimator.py
src/gluonts/time_feature/_base.py

Backporting bug fixes to 0.9.x.
* #1903
* #1909

Backports v0.9.x 2022 02 28

---

requirements/requirements-docs.txt

*Description of changes:* Updating requirements for the docs build, which otherwise block any PR (due to some problem with `ipython_genutils` which I understand was deprecated and unused in newer versions).

Update docs requirements

---

src/gluonts/torch/model/deepar/estimator.py

DeepAR PyTorch: make samplers configurable

---

src/gluonts/torch/model/simple_feedforward/estimator.py
src/gluonts/torch/model/simple_feedforward/module.py

Fix: remove unused freq from SimpleFeedForward

---

docs/tutorials/forecasting/howto_pytorch_lightning.md

Fix Pytorch Lightning tutorial.

---

docs/tutorials/forecasting/howto_pytorch_lightning.md
src/gluonts/model/estimator.py
src/gluonts/mx/distribution/isqf.py
src/gluonts/mx/distribution/transformed_distribution.py

Backporting fixes:
* #1920 
* #1931
* #1933
* #1938

Backports for 0.9.3

---

src/gluonts/model/tft/_estimator.py
src/gluonts/model/tft/_network.py
test/model/tft/test_model.py

*Issue #, if available:* Fixes #1944

Fix forecast keys (quantiles) output by TemporalFusionTransformer

---

src/gluonts/model/tft/_estimator.py
src/gluonts/mx/distribution/beta.py
src/gluonts/mx/distribution/distribution_output.py
src/gluonts/mx/distribution/gamma.py
src/gluonts/mx/distribution/gaussian.py
src/gluonts/mx/distribution/genpareto.py
src/gluonts/mx/distribution/inflated_beta.py
src/gluonts/mx/distribution/laplace.py
src/gluonts/mx/distribution/logit_normal.py
src/gluonts/mx/distribution/neg_binomial.py
src/gluonts/mx/distribution/poisson.py
src/gluonts/mx/distribution/student_t.py
test/model/tft/test_model.py

Backporting fixes:
* #1950 
* #1952 

Backports for 0.9.4

---

src/gluonts/torch/model/deepar/module.py

Remove unnecessary lines in torch DeepAR network

---

src/gluonts/dataset/common.py
src/gluonts/dataset/util.py
src/gluonts/evaluation/backtest.py
src/gluonts/model/forecast_generator.py
src/gluonts/transform/feature.py

use FieldName

---

requirements/requirements-pytorch.txt

Pin protobuf version.

---

src/gluonts/dataset/split/splitter.py
test/dataset/split/test_split.py

*Issue #, if available:* Fixes #1984 

Fix OffsetSplitter for negative offsets

---

docs/tutorials/hyperparameter_tuning/hp_tuning_with_optuna.md
docs/tutorials/index.rst
requirements/requirements-docs.txt

Add HP tuning example with Optuna

---

src/gluonts/evaluation/_base.py

In this PR we compute ND for item_metrics, as currently it is only available for aggregated metrics.

add ND for item_metrics

---

src/gluonts/itertools.py
test/test_itertools.py

Rework `itertools`, add col-to-row and row-to-col functions.

---

src/gluonts/dataset/common.py

Re-add cache for parsing 'pd.Period'.

---

src/gluonts/torch/distributions/affine_transformed.py
test/torch/distribution/test_affine_transformed.py

*Issue #, if available:* Related to #2015

Fix torch affine transformed distribution

---

src/gluonts/core/settings.py
test/core/test_settings.py

Settings._let will pop element it added instead of just the last one.
